In [11]:

import cv2
import numpy as np

# Load the image
image = cv2.imread('j.png')

# Convert the image to HSV color space
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Define the range of purple color in HSV
lower_purple = np.array([122, 104, 65])
upper_purple = np.array([141, 200, 255])

# Create a mask to detect purple color
mask = cv2.inRange(hsv, lower_purple, upper_purple)

# Find contours in the mask
contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# Draw contours on the original image
for contour in contours:
    cv2.drawContours(image, [contour], -1, (0, 255, 0), 3)

# Save the result
cv2.imwrite('image_with_purple_pixels.jpg', image)

# Print a success message
print("Successfully detected and highlighted purple pixels in the image.")



Successfully detected and highlighted purple pixels in the image.


In [10]:
#滑轨得到
import cv2
import numpy as np

def nothing(x):
    pass

# 创建一个窗口
cv2.namedWindow('image')

# 创建滑动条，用于调整颜色阈值
cv2.createTrackbar('LowerB', 'image', 0, 255, nothing)
cv2.createTrackbar('LowerG', 'image', 0, 255, nothing)
cv2.createTrackbar('LowerR', 'image', 0, 255, nothing)
cv2.createTrackbar('UpperB', 'image', 255, 255, nothing)
cv2.createTrackbar('UpperG', 'image', 255, 255, nothing)
cv2.createTrackbar('UpperR', 'image', 255, 255, nothing)

# 设置默认的颜色阈值
cv2.setTrackbarPos('LowerB', 'image', 128)
cv2.setTrackbarPos('LowerG', 'image', 0)
cv2.setTrackbarPos('LowerR', 'image', 128)
cv2.setTrackbarPos('UpperB', 'image', 147)
cv2.setTrackbarPos('UpperG', 'image', 112)
cv2.setTrackbarPos('UpperR', 'image', 219)

while True:
    # 获取滑动条的值
    lower_blue = np.array([cv2.getTrackbarPos('LowerB', 'image'),
                           cv2.getTrackbarPos('LowerG', 'image'),
                           cv2.getTrackbarPos('LowerR', 'image')])
    upper_blue = np.array([cv2.getTrackbarPos('UpperB', 'image'),
                           cv2.getTrackbarPos('UpperG', 'image'),
                           cv2.getTrackbarPos('UpperR', 'image')])

    # 这里加载你的图片
    frame = cv2.imread('j.png')
    
    # 转换到HSV
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    # 根据阈值构建掩码
    mask = cv2.inRange(hsv, lower_blue, upper_blue)
    
    # 将掩码和图片逐像素相加
    result = cv2.bitwise_and(frame, frame, mask=mask)

    # 将结果转换为二值图像
    result_binary = cv2.cvtColor(result, cv2.COLOR_BGR2GRAY)
    _, result_binary = cv2.threshold(result_binary, 1, 255, cv2.THRESH_BINARY)

    # 显示图片
    result_binary = cv2.resize(result_binary, (640, 480))
    cv2.imshow('image', result_binary)
    
    k = cv2.waitKey(1) & 0xFF
    if k == 27:  # 按 'ESC' 退出
        break

# 关闭所有窗口
cv2.destroyAllWindows()

#


error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2561: error: (-27:Null pointer) NULL window: 'image' in function 'cvGetTrackbarPos'


In [2]:
#减除后的图像
import cv2
# Load the images
image1 = cv2.imread('j_w.png')
image2 = cv2.imread('j.png')
print(image1.shape)
print(image2.shape)
# Check if the images have the same size and the same number of channels
if image1.shape != image2.shape:
    print("Error: Sizes of input images do not match!")
else:
    # Subtract the images
    diff = cv2.subtract(image2, image1)

    # Save the result
    cv2.imwrite('diff_image.jpg', diff)


(1944, 2592, 3)
(1944, 2592, 3)


In [7]:
# 找到基准线和最大亮度
import cv2
import numpy as np
image = cv2.imread('diff_image.jpg')
print(image.shape) #(1944, 2592, 3)
# 反转颜色
#image = cv2.bitwise_not(image) # 反转颜色
# 二值化 
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) # 转换为灰度图像  #0是黑色，255是白色
m =[]
for i in range(gray.shape[0]): #行数
    # 找到每一行最大亮度的索引
    #print(np.argmax(gray[i]),np.max(gray[i]))
    if np.max(gray[i])>20:
        # 将最大值像素 置为255
        gray[i][np.argmax(gray[i])]=255
        # 其余的像素置为0
        gray[i][:np.argmax(gray[i])]=0
        gray[i][np.argmax(gray[i])+1:]=0
        m.append(np.argmax(gray[i]))
    else:
        # 其余的像素置为0
        gray[i][:]=0

print(m) #索引的列表
m = list(set(m))
# 从小到大排序
m.sort()
print(m[0],m[1])
print(min(m),max(m))

points =[]
for i in range(gray.shape[0]): #行数
    if np.max(gray[i]) !=0:
        points.append([i,np.argmax(gray[i]),np.argmax(gray[i])-min(m)])
    gray[i][min(m)]=255 #显示用
print(points)
    



for i in range(image.shape[0]): #行数
    image[i][min(m)] = [255,255,255]
# 显示
cv2.namedWindow('binary', cv2.WINDOW_NORMAL)# 显示的图像可拉伸
cv2.namedWindow('image', cv2.WINDOW_NORMAL)# 显示的图像可拉伸
cv2.resizeWindow('binary', 640, 480)
cv2.imshow('image', image)
cv2.imshow('binary', gray)
cv2.waitKey(0)
# # 膨胀
# kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
# binary = cv2.dilate(binary, kernel)







(1944, 2592, 3)
[1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1026, 1026, 1025, 1025, 1026, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1024, 1024, 1024, 1024, 1025, 1025, 1025, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,

In [1]:
import open3d as o3d
import numpy as np

# 假设有一个包含点数据的列表，每个元素都是(x, y, depth)的形式

# (像素的横坐标, 像素的纵坐标, 深度信息)

point_data = [[4, 1064, 48], [5, 1064, 48], [6, 1064, 48], [7, 1064, 48], [8, 1064, 48], [9, 1064, 48], [10, 1064, 48], [11, 1064, 48], [20, 1026, 10], [21, 1026, 10], [22, 1025, 9], [23, 1025, 9], [24, 1026, 10], [25, 1025, 9], [26, 1025, 9], [27, 1025, 9], [28, 1025, 9], [29, 1025, 9], [30, 1025, 9], [31, 1025, 9], [32, 1025, 9], [33, 1025, 9], [34, 1025, 9], [35, 1025, 9], [36, 1025, 9], [37, 1025, 9], [38, 1025, 9], [39, 1025, 9], [40, 1025, 9], [41, 1025, 9], [42, 1025, 9], [43, 1025, 9], [44, 1025, 9], [45, 1025, 9], [46, 1025, 9], [47, 1025, 9], [48, 1025, 9], [49, 1025, 9], [50, 1025, 9], [51, 1025, 9], [52, 1025, 9], [53, 1025, 9], [54, 1025, 9], [55, 1025, 9], [56, 1025, 9], [57, 1025, 9], [58, 1025, 9], [59, 1025, 9], [60, 1025, 9], [61, 1025, 9], [62, 1025, 9], [63, 1025, 9], [64, 1025, 9], [65, 1025, 9], [66, 1025, 9], [67, 1025, 9], [68, 1025, 9], [69, 1025, 9], [70, 1025, 9], [71, 1025, 9], [72, 1025, 9], [73, 1025, 9], [74, 1025, 9], [75, 1025, 9], [76, 1025, 9], [77, 1025, 9], [78, 1025, 9], [79, 1025, 9], [80, 1025, 9], [81, 1025, 9], [82, 1025, 9], [83, 1025, 9], [84, 1025, 9], [85, 1025, 9], [86, 1025, 9], [87, 1025, 9], [88, 1025, 9], [89, 1025, 9], [90, 1025, 9], [91, 1025, 9], [92, 1025, 9], [93, 1025, 9], [94, 1025, 9], [95, 1025, 9], [96, 1025, 9], [97, 1025, 9], [98, 1025, 9], [99, 1025, 9], [100, 1025, 9], [101, 1025, 9], [102, 1025, 9], [103, 1025, 9], [104, 1025, 9], [105, 1025, 9], [106, 1025, 9], [107, 1024, 8], [108, 1024, 8], [109, 1024, 8], [110, 1024, 8], [111, 1025, 9], [112, 1025, 9], [113, 1025, 9], [114, 1024, 8], [115, 1024, 8], [116, 1024, 8], [117, 1024, 8], [118, 1024, 8], [119, 1024, 8], [120, 1024, 8], [121, 1024, 8], [122, 1024, 8], [123, 1024, 8], [124, 1024, 8], [125, 1024, 8], [126, 1024, 8], [127, 1024, 8], [128, 1024, 8], [129, 1024, 8], [130, 1024, 8], [131, 1024, 8], [132, 1024, 8], [133, 1024, 8], [134, 1024, 8], [135, 1024, 8], [136, 1024, 8], [137, 1024, 8], [138, 1024, 8], [139, 1024, 8], [140, 1024, 8], [141, 1024, 8], [142, 1024, 8], [143, 1024, 8], [144, 1024, 8], [145, 1024, 8], [146, 1024, 8], [147, 1024, 8], [148, 1024, 8], [149, 1024, 8], [150, 1024, 8], [151, 1024, 8], [152, 1024, 8], [153, 1024, 8], [154, 1024, 8], [155, 1024, 8], [156, 1024, 8], [157, 1024, 8], [158, 1024, 8], [159, 1024, 8], [160, 1024, 8], [161, 1024, 8], [162, 1024, 8], [163, 1024, 8], [164, 1024, 8], [165, 1024, 8], [166, 1024, 8], [167, 1024, 8], [168, 1024, 8], [169, 1024, 8], [170, 1024, 8], [171, 1024, 8], [172, 1024, 8], [173, 1024, 8], [174, 1024, 8], [175, 1024, 8], [176, 1024, 8], [177, 1024, 8], [178, 1024, 8], [179, 1024, 8], [180, 1024, 8], [181, 1024, 8], [182, 1024, 8], [183, 1024, 8], [184, 1024, 8], [185, 1024, 8], [186, 1024, 8], [187, 1024, 8], [188, 1024, 8], [189, 1024, 8], [190, 1024, 8], [191, 1023, 7], [192, 1024, 8], [193, 1024, 8], [194, 1024, 8], [195, 1024, 8], [196, 1024, 8], [197, 1024, 8], [198, 1023, 7], [199, 1023, 7], [200, 1024, 8], [201, 1023, 7], [202, 1023, 7], [203, 1023, 7], [204, 1023, 7], [205, 1023, 7], [206, 1023, 7], [207, 1023, 7], [208, 1023, 7], [209, 1023, 7], [210, 1023, 7], [211, 1023, 7], [212, 1023, 7], [213, 1023, 7], [214, 1023, 7], [215, 1023, 7], [216, 1023, 7], [217, 1023, 7], [218, 1023, 7], [219, 1023, 7], [220, 1023, 7], [221, 1023, 7], [222, 1023, 7], [223, 1023, 7], [224, 1023, 7], [225, 1023, 7], [226, 1023, 7], [227, 1023, 7], [228, 1023, 7], [229, 1023, 7], [230, 1023, 7], [231, 1023, 7], [232, 1023, 7], [233, 1023, 7], [234, 1023, 7], [235, 1023, 7], [236, 1023, 7], [237, 1023, 7], [238, 1023, 7], [239, 1023, 7], [240, 1023, 7], [241, 1023, 7], [242, 1023, 7], [243, 1023, 7], [244, 1023, 7], [245, 1023, 7], [246, 1023, 7], [247, 1023, 7], [248, 1023, 7], [249, 1023, 7], [250, 1023, 7], [251, 1023, 7], [252, 1023, 7], [253, 1023, 7], [254, 1023, 7], [255, 1023, 7], [256, 1023, 7], [257, 1023, 7], [258, 1023, 7], [259, 1023, 7], [260, 1023, 7], [261, 1023, 7], [262, 1023, 7], [263, 1023, 7], [264, 1023, 7], [265, 1023, 7], [266, 1023, 7], [267, 1023, 7], [268, 1023, 7], [269, 1023, 7], [270, 1023, 7], [271, 1023, 7], [272, 1023, 7], [273, 1023, 7], [274, 1023, 7], [275, 1023, 7], [276, 1023, 7], [277, 1023, 7], [278, 1023, 7], [279, 1023, 7], [280, 1023, 7], [281, 1023, 7], [282, 1023, 7], [283, 1023, 7], [284, 1023, 7], [285, 1023, 7], [286, 1023, 7], [287, 1023, 7], [288, 1023, 7], [289, 1023, 7], [290, 1023, 7], [291, 1022, 6], [292, 1022, 6], [293, 1022, 6], [294, 1022, 6], [295, 1022, 6], [296, 1023, 7], [297, 1023, 7], [298, 1023, 7], [299, 1023, 7], [305, 1028, 12], [306, 1028, 12], [307, 1028, 12], [308, 1028, 12], [309, 1028, 12], [310, 1028, 12], [313, 1028, 12], [314, 1028, 12], [315, 1028, 12], [316, 1028, 12], [317, 1028, 12], [318, 1029, 13], [319, 1029, 13], [325, 1031, 15], [326, 1031, 15], [327, 1031, 15], [329, 1030, 14], [330, 1031, 15], [331, 1031, 15], [340, 1033, 17], [341, 1033, 17], [345, 1034, 18], [346, 1035, 19], [347, 1035, 19], [348, 1035, 19], [349, 1035, 19], [350, 1035, 19], [351, 1035, 19], [352, 1036, 20], [353, 1036, 20], [354, 1036, 20], [368, 1042, 26], [369, 1042, 26], [370, 1042, 26], [371, 1042, 26], [394, 1052, 36], [395, 1052, 36], [396, 1052, 36], [397, 1051, 35], [398, 1051, 35], [399, 1051, 35], [400, 1051, 35], [401, 1051, 35], [402, 1051, 35], [403, 1051, 35], [404, 1052, 36], [405, 1052, 36], [406, 1051, 35], [407, 1051, 35], [408, 1051, 35], [409, 1051, 35], [410, 1051, 35], [411, 1051, 35], [412, 1051, 35], [414, 1050, 34], [415, 1050, 34], [416, 1051, 35], [417, 1051, 35], [418, 1051, 35], [419, 1051, 35], [420, 1051, 35], [421, 1051, 35], [422, 1051, 35], [423, 1050, 34], [424, 1051, 35], [425, 1051, 35], [426, 1051, 35], [427, 1051, 35], [428, 1051, 35], [429, 1051, 35], [430, 1051, 35], [431, 1051, 35], [432, 1051, 35], [433, 1051, 35], [434, 1051, 35], [435, 1051, 35], [436, 1051, 35], [437, 1051, 35], [438, 1051, 35], [439, 1051, 35], [440, 1050, 34], [441, 1050, 34], [442, 1050, 34], [443, 1051, 35], [444, 1051, 35], [445, 1051, 35], [446, 1052, 36], [447, 1051, 35], [448, 1051, 35], [449, 1051, 35], [450, 1051, 35], [451, 1050, 34], [452, 1050, 34], [453, 1050, 34], [454, 1051, 35], [455, 1051, 35], [456, 1051, 35], [457, 1051, 35], [458, 1051, 35], [459, 1051, 35], [460, 1051, 35], [461, 1051, 35], [462, 1050, 34], [463, 1050, 34], [464, 1051, 35], [465, 1051, 35], [466, 1051, 35], [467, 1051, 35], [468, 1051, 35], [469, 1051, 35], [470, 1051, 35], [471, 1051, 35], [472, 1051, 35], [473, 1051, 35], [474, 1051, 35], [475, 1051, 35], [476, 1051, 35], [477, 1051, 35], [478, 1051, 35], [479, 1051, 35], [480, 1051, 35], [481, 1051, 35], [482, 1051, 35], [483, 1051, 35], [484, 1051, 35], [485, 1051, 35], [486, 1051, 35], [487, 1051, 35], [488, 1051, 35], [489, 1051, 35], [490, 1051, 35], [491, 1051, 35], [492, 1051, 35], [493, 1051, 35], [494, 1051, 35], [495, 1051, 35], [496, 1051, 35], [497, 1051, 35], [498, 1050, 34], [499, 1052, 36], [500, 1052, 36], [501, 1052, 36], [502, 1050, 34], [503, 1050, 34], [504, 1051, 35], [505, 1051, 35], [506, 1051, 35], [507, 1051, 35], [508, 1051, 35], [509, 1051, 35], [510, 1051, 35], [511, 1051, 35], [512, 1051, 35], [513, 1051, 35], [514, 1051, 35], [515, 1051, 35], [516, 1050, 34], [517, 1051, 35], [518, 1051, 35], [519, 1051, 35], [520, 1051, 35], [521, 1051, 35], [522, 1051, 35], [523, 1051, 35], [524, 1051, 35], [525, 1051, 35], [526, 1051, 35], [527, 1051, 35], [528, 1050, 34], [529, 1050, 34], [530, 1050, 34], [531, 1050, 34], [532, 1050, 34], [533, 1050, 34], [534, 1050, 34], [535, 1050, 34], [536, 1050, 34], [537, 1050, 34], [538, 1050, 34], [539, 1050, 34], [540, 1050, 34], [541, 1050, 34], [542, 1050, 34], [543, 1050, 34], [544, 1051, 35], [545, 1051, 35], [546, 1051, 35], [547, 1051, 35], [548, 1051, 35], [549, 1051, 35], [550, 1051, 35], [551, 1051, 35], [552, 1051, 35], [553, 1051, 35], [554, 1050, 34], [555, 1051, 35], [556, 1051, 35], [557, 1051, 35], [558, 1051, 35], [559, 1051, 35], [560, 1051, 35], [561, 1051, 35], [562, 1051, 35], [563, 1051, 35], [564, 1051, 35], [565, 1051, 35], [566, 1051, 35], [567, 1051, 35], [568, 1050, 34], [569, 1050, 34], [570, 1050, 34], [571, 1050, 34], [572, 1050, 34], [573, 1050, 34], [574, 1050, 34], [575, 1050, 34], [576, 1050, 34], [577, 1050, 34], [578, 1050, 34], [579, 1050, 34], [580, 1050, 34], [581, 1050, 34], [582, 1050, 34], [583, 1050, 34], [584, 1050, 34], [585, 1050, 34], [586, 1051, 35], [587, 1051, 35], [588, 1051, 35], [589, 1050, 34], [590, 1050, 34], [591, 1050, 34], [592, 1051, 35], [593, 1050, 34], [594, 1050, 34], [595, 1050, 34], [596, 1051, 35], [597, 1051, 35], [598, 1051, 35], [599, 1051, 35], [600, 1051, 35], [601, 1050, 34], [602, 1050, 34], [603, 1050, 34], [604, 1051, 35], [605, 1050, 34], [606, 1051, 35], [607, 1051, 35], [608, 1051, 35], [609, 1051, 35], [610, 1051, 35], [611, 1051, 35], [612, 1050, 34], [613, 1050, 34], [614, 1050, 34], [615, 1050, 34], [616, 1050, 34], [617, 1050, 34], [618, 1050, 34], [619, 1050, 34], [620, 1050, 34], [621, 1050, 34], [622, 1050, 34], [623, 1050, 34], [624, 1050, 34], [625, 1050, 34], [626, 1050, 34], [627, 1050, 34], [628, 1050, 34], [629, 1050, 34], [630, 1051, 35], [631, 1051, 35], [632, 1051, 35], [633, 1050, 34], [634, 1050, 34], [635, 1050, 34], [636, 1050, 34], [637, 1050, 34], [638, 1050, 34], [639, 1050, 34], [640, 1051, 35], [641, 1051, 35], [642, 1051, 35], [643, 1050, 34], [644, 1050, 34], [645, 1050, 34], [646, 1050, 34], [647, 1050, 34], [648, 1050, 34], [649, 1050, 34], [650, 1050, 34], [651, 1050, 34], [652, 1050, 34], [653, 1050, 34], [654, 1050, 34], [655, 1050, 34], [656, 1050, 34], [657, 1050, 34], [658, 1050, 34], [659, 1050, 34], [660, 1050, 34], [661, 1050, 34], [662, 1050, 34], [663, 1050, 34], [664, 1050, 34], [665, 1050, 34], [666, 1051, 35], [667, 1050, 34], [668, 1050, 34], [669, 1050, 34], [670, 1050, 34], [671, 1050, 34], [672, 1050, 34], [673, 1049, 33], [674, 1049, 33], [675, 1049, 33], [676, 1049, 33], [677, 1049, 33], [678, 1049, 33], [679, 1049, 33], [680, 1049, 33], [681, 1049, 33], [682, 1049, 33], [683, 1049, 33], [684, 1049, 33], [685, 1049, 33], [686, 1049, 33], [687, 1049, 33], [688, 1049, 33], [689, 1049, 33], [690, 1049, 33], [691, 1049, 33], [692, 1049, 33], [693, 1049, 33], [694, 1049, 33], [695, 1049, 33], [696, 1049, 33], [697, 1049, 33], [698, 1049, 33], [699, 1049, 33], [700, 1049, 33], [701, 1049, 33], [702, 1049, 33], [703, 1049, 33], [704, 1048, 32], [705, 1048, 32], [706, 1048, 32], [707, 1048, 32], [708, 1048, 32], [709, 1048, 32], [710, 1048, 32], [711, 1047, 31], [712, 1047, 31], [713, 1047, 31], [714, 1047, 31], [715, 1047, 31], [716, 1047, 31], [717, 1047, 31], [718, 1047, 31], [719, 1047, 31], [720, 1047, 31], [721, 1047, 31], [722, 1047, 31], [723, 1047, 31], [724, 1047, 31], [725, 1047, 31], [726, 1047, 31], [727, 1047, 31], [728, 1047, 31], [729, 1047, 31], [730, 1047, 31], [731, 1047, 31], [732, 1047, 31], [733, 1047, 31], [734, 1047, 31], [735, 1047, 31], [736, 1047, 31], [737, 1047, 31], [738, 1047, 31], [739, 1047, 31], [740, 1047, 31], [741, 1047, 31], [742, 1047, 31], [743, 1047, 31], [744, 1047, 31], [745, 1047, 31], [746, 1047, 31], [747, 1047, 31], [748, 1047, 31], [749, 1047, 31], [750, 1047, 31], [751, 1047, 31], [752, 1047, 31], [753, 1047, 31], [754, 1047, 31], [755, 1047, 31], [756, 1047, 31], [757, 1047, 31], [758, 1047, 31], [759, 1047, 31], [760, 1047, 31], [761, 1047, 31], [762, 1047, 31], [763, 1047, 31], [764, 1047, 31], [765, 1047, 31], [766, 1047, 31], [767, 1047, 31], [768, 1047, 31], [769, 1047, 31], [770, 1047, 31], [771, 1047, 31], [772, 1047, 31], [773, 1047, 31], [774, 1047, 31], [775, 1047, 31], [776, 1047, 31], [777, 1047, 31], [778, 1047, 31], [779, 1047, 31], [780, 1047, 31], [781, 1047, 31], [782, 1047, 31], [783, 1047, 31], [784, 1047, 31], [785, 1047, 31], [786, 1047, 31], [787, 1047, 31], [788, 1047, 31], [789, 1047, 31], [790, 1047, 31], [791, 1046, 30], [792, 1047, 31], [793, 1047, 31], [794, 1047, 31], [795, 1047, 31], [796, 1047, 31], [797, 1047, 31], [798, 1047, 31], [799, 1047, 31], [800, 1047, 31], [801, 1047, 31], [802, 1047, 31], [803, 1047, 31], [804, 1047, 31], [805, 1047, 31], [806, 1046, 30], [807, 1046, 30], [808, 1047, 31], [809, 1047, 31], [810, 1048, 32], [811, 1047, 31], [812, 1048, 32], [813, 1047, 31], [814, 1048, 32], [815, 1047, 31], [816, 1047, 31], [817, 1047, 31], [818, 1047, 31], [819, 1047, 31], [820, 1047, 31], [821, 1047, 31], [822, 1047, 31], [823, 1047, 31], [824, 1047, 31], [825, 1047, 31], [826, 1048, 32], [827, 1048, 32], [828, 1046, 30], [829, 1046, 30], [830, 1048, 32], [831, 1048, 32], [832, 1048, 32], [833, 1047, 31], [834, 1049, 33], [835, 1046, 30], [836, 1046, 30], [837, 1046, 30], [838, 1046, 30], [839, 1048, 32], [840, 1048, 32], [841, 1047, 31], [842, 1047, 31], [843, 1047, 31], [844, 1047, 31], [845, 1048, 32], [846, 1048, 32], [847, 1048, 32], [848, 1048, 32], [849, 1048, 32], [850, 1048, 32], [851, 1048, 32], [852, 1048, 32], [853, 1048, 32], [854, 1047, 31], [855, 1047, 31], [856, 1048, 32], [857, 1048, 32], [858, 1048, 32], [859, 1048, 32], [860, 1048, 32], [861, 1047, 31], [862, 1047, 31], [863, 1047, 31], [864, 1048, 32], [865, 1047, 31], [866, 1047, 31], [867, 1047, 31], [868, 1047, 31], [869, 1047, 31], [870, 1047, 31], [871, 1047, 31], [872, 1048, 32], [873, 1047, 31], [874, 1049, 33], [875, 1048, 32], [876, 1047, 31], [877, 1047, 31], [878, 1047, 31], [879, 1047, 31], [880, 1047, 31], [881, 1047, 31], [882, 1047, 31], [883, 1047, 31], [884, 1047, 31], [885, 1048, 32], [886, 1047, 31], [887, 1047, 31], [888, 1047, 31], [889, 1047, 31], [890, 1047, 31], [891, 1046, 30], [892, 1046, 30], [893, 1046, 30], [894, 1047, 31], [895, 1047, 31], [896, 1046, 30], [897, 1046, 30], [898, 1046, 30], [899, 1046, 30], [900, 1046, 30], [901, 1046, 30], [902, 1046, 30], [903, 1046, 30], [904, 1045, 29], [905, 1045, 29], [906, 1045, 29], [907, 1045, 29], [908, 1045, 29], [909, 1045, 29], [910, 1045, 29], [911, 1045, 29], [912, 1045, 29], [913, 1045, 29], [914, 1045, 29], [915, 1045, 29], [916, 1045, 29], [917, 1045, 29], [918, 1045, 29], [919, 1045, 29], [920, 1045, 29], [921, 1045, 29], [922, 1045, 29], [923, 1045, 29], [924, 1045, 29], [925, 1045, 29], [926, 1045, 29], [927, 1045, 29], [928, 1045, 29], [929, 1045, 29], [930, 1045, 29], [931, 1045, 29], [932, 1045, 29], [933, 1045, 29], [934, 1045, 29], [935, 1045, 29], [936, 1045, 29], [937, 1045, 29], [938, 1045, 29], [939, 1045, 29], [940, 1045, 29], [941, 1045, 29], [942, 1045, 29], [943, 1045, 29], [944, 1045, 29], [945, 1045, 29], [946, 1045, 29], [947, 1045, 29], [948, 1045, 29], [949, 1045, 29], [950, 1045, 29], [951, 1045, 29], [952, 1045, 29], [953, 1045, 29], [954, 1045, 29], [955, 1045, 29], [956, 1045, 29], [957, 1045, 29], [958, 1045, 29], [959, 1045, 29], [960, 1045, 29], [961, 1045, 29], [962, 1045, 29], [963, 1045, 29], [964, 1045, 29], [965, 1045, 29], [966, 1045, 29], [967, 1045, 29], [968, 1045, 29], [969, 1045, 29], [970, 1045, 29], [971, 1045, 29], [972, 1045, 29], [973, 1045, 29], [974, 1045, 29], [975, 1045, 29], [976, 1045, 29], [977, 1045, 29], [978, 1045, 29], [979, 1045, 29], [980, 1045, 29], [981, 1045, 29], [982, 1045, 29], [983, 1045, 29], [984, 1045, 29], [985, 1045, 29], [986, 1045, 29], [987, 1045, 29], [988, 1045, 29], [989, 1045, 29], [990, 1045, 29], [991, 1044, 28], [992, 1045, 29], [993, 1045, 29], [994, 1045, 29], [995, 1045, 29], [996, 1045, 29], [997, 1045, 29], [998, 1045, 29], [999, 1045, 29], [1000, 1045, 29], [1001, 1044, 28], [1002, 1044, 28], [1003, 1045, 29], [1004, 1045, 29], [1005, 1045, 29], [1006, 1045, 29], [1007, 1045, 29], [1008, 1045, 29], [1009, 1044, 28], [1010, 1045, 29], [1011, 1045, 29], [1012, 1045, 29], [1013, 1045, 29], [1014, 1045, 29], [1015, 1045, 29], [1016, 1046, 30], [1017, 1045, 29], [1018, 1046, 30], [1019, 1045, 29], [1020, 1045, 29], [1021, 1046, 30], [1022, 1045, 29], [1023, 1045, 29], [1024, 1045, 29], [1025, 1045, 29], [1026, 1045, 29], [1027, 1045, 29], [1028, 1046, 30], [1029, 1045, 29], [1030, 1045, 29], [1031, 1045, 29], [1032, 1046, 30], [1033, 1046, 30], [1034, 1047, 31], [1035, 1046, 30], [1036, 1045, 29], [1037, 1045, 29], [1038, 1045, 29], [1039, 1045, 29], [1040, 1046, 30], [1041, 1045, 29], [1042, 1045, 29], [1043, 1045, 29], [1044, 1045, 29], [1045, 1046, 30], [1046, 1046, 30], [1047, 1046, 30], [1048, 1045, 29], [1049, 1045, 29], [1050, 1045, 29], [1051, 1045, 29], [1052, 1045, 29], [1053, 1045, 29], [1054, 1045, 29], [1055, 1045, 29], [1056, 1046, 30], [1057, 1046, 30], [1058, 1046, 30], [1059, 1046, 30], [1060, 1046, 30], [1061, 1046, 30], [1062, 1045, 29], [1063, 1046, 30], [1064, 1045, 29], [1065, 1045, 29], [1066, 1045, 29], [1067, 1045, 29], [1068, 1045, 29], [1069, 1045, 29], [1070, 1045, 29], [1071, 1045, 29], [1072, 1045, 29], [1073, 1045, 29], [1074, 1045, 29], [1075, 1045, 29], [1076, 1045, 29], [1077, 1045, 29], [1078, 1045, 29], [1079, 1045, 29], [1080, 1046, 30], [1081, 1046, 30], [1082, 1046, 30], [1083, 1046, 30], [1084, 1046, 30], [1085, 1046, 30], [1086, 1046, 30], [1087, 1046, 30], [1088, 1046, 30], [1089, 1046, 30], [1090, 1046, 30], [1091, 1046, 30], [1092, 1046, 30], [1093, 1046, 30], [1094, 1047, 31], [1095, 1047, 31], [1096, 1047, 31], [1097, 1047, 31], [1098, 1047, 31], [1099, 1047, 31], [1100, 1047, 31], [1101, 1047, 31], [1102, 1047, 31], [1103, 1046, 30], [1104, 1046, 30], [1105, 1047, 31], [1106, 1047, 31], [1107, 1047, 31], [1108, 1047, 31], [1109, 1047, 31], [1110, 1047, 31], [1111, 1047, 31], [1112, 1047, 31], [1113, 1047, 31], [1114, 1047, 31], [1115, 1047, 31], [1116, 1047, 31], [1117, 1047, 31], [1118, 1047, 31], [1119, 1047, 31], [1120, 1047, 31], [1121, 1047, 31], [1122, 1047, 31], [1123, 1047, 31], [1124, 1047, 31], [1125, 1047, 31], [1126, 1047, 31], [1127, 1047, 31], [1128, 1047, 31], [1129, 1048, 32], [1130, 1048, 32], [1131, 1048, 32], [1132, 1048, 32], [1133, 1048, 32], [1134, 1048, 32], [1135, 1048, 32], [1136, 1048, 32], [1137, 1048, 32], [1138, 1048, 32], [1139, 1048, 32], [1140, 1048, 32], [1141, 1048, 32], [1142, 1048, 32], [1143, 1049, 33], [1144, 1049, 33], [1145, 1049, 33], [1146, 1049, 33], [1147, 1049, 33], [1148, 1049, 33], [1149, 1049, 33], [1150, 1049, 33], [1151, 1049, 33], [1152, 1049, 33], [1153, 1049, 33], [1154, 1050, 34], [1155, 1050, 34], [1156, 1049, 33], [1157, 1049, 33], [1158, 1049, 33], [1159, 1049, 33], [1160, 1049, 33], [1161, 1049, 33], [1162, 1049, 33], [1163, 1049, 33], [1164, 1049, 33], [1165, 1050, 34], [1166, 1050, 34], [1167, 1050, 34], [1168, 1049, 33], [1169, 1049, 33], [1170, 1049, 33], [1171, 1049, 33], [1172, 1049, 33], [1173, 1050, 34], [1174, 1050, 34], [1175, 1050, 34], [1176, 1050, 34], [1177, 1050, 34], [1178, 1050, 34], [1179, 1050, 34], [1180, 1050, 34], [1181, 1050, 34], [1182, 1050, 34], [1183, 1049, 33], [1184, 1049, 33], [1185, 1049, 33], [1186, 1049, 33], [1187, 1049, 33], [1188, 1049, 33], [1189, 1049, 33], [1190, 1049, 33], [1191, 1049, 33], [1192, 1049, 33], [1193, 1049, 33], [1194, 1049, 33], [1195, 1049, 33], [1196, 1049, 33], [1197, 1049, 33], [1198, 1050, 34], [1199, 1050, 34], [1200, 1050, 34], [1201, 1050, 34], [1202, 1049, 33], [1203, 1049, 33], [1204, 1049, 33], [1205, 1049, 33], [1206, 1049, 33], [1207, 1049, 33], [1208, 1049, 33], [1209, 1049, 33], [1210, 1049, 33], [1211, 1049, 33], [1212, 1049, 33], [1213, 1049, 33], [1214, 1050, 34], [1215, 1050, 34], [1216, 1050, 34], [1217, 1049, 33], [1218, 1049, 33], [1219, 1049, 33], [1220, 1049, 33], [1221, 1049, 33], [1222, 1049, 33], [1223, 1050, 34], [1224, 1050, 34], [1225, 1050, 34], [1226, 1050, 34], [1227, 1049, 33], [1228, 1049, 33], [1229, 1049, 33], [1230, 1049, 33], [1231, 1049, 33], [1232, 1050, 34], [1233, 1050, 34], [1234, 1050, 34], [1235, 1050, 34], [1236, 1050, 34], [1237, 1050, 34], [1238, 1050, 34], [1239, 1050, 34], [1240, 1050, 34], [1241, 1050, 34], [1242, 1049, 33], [1243, 1049, 33], [1244, 1050, 34], [1245, 1050, 34], [1246, 1050, 34], [1247, 1050, 34], [1248, 1050, 34], [1249, 1050, 34], [1250, 1050, 34], [1251, 1050, 34], [1252, 1050, 34], [1253, 1050, 34], [1254, 1049, 33], [1255, 1049, 33], [1256, 1049, 33], [1257, 1049, 33], [1258, 1049, 33], [1259, 1049, 33], [1260, 1049, 33], [1261, 1049, 33], [1262, 1049, 33], [1263, 1049, 33], [1264, 1049, 33], [1265, 1049, 33], [1266, 1049, 33], [1267, 1049, 33], [1268, 1049, 33], [1269, 1049, 33], [1270, 1049, 33], [1271, 1049, 33], [1272, 1049, 33], [1273, 1049, 33], [1274, 1049, 33], [1275, 1049, 33], [1276, 1049, 33], [1277, 1049, 33], [1278, 1049, 33], [1279, 1049, 33], [1280, 1049, 33], [1281, 1049, 33], [1282, 1049, 33], [1283, 1049, 33], [1284, 1049, 33], [1285, 1049, 33], [1286, 1049, 33], [1287, 1049, 33], [1288, 1049, 33], [1289, 1049, 33], [1290, 1049, 33], [1291, 1049, 33], [1292, 1049, 33], [1293, 1049, 33], [1294, 1049, 33], [1295, 1049, 33], [1296, 1049, 33], [1297, 1049, 33], [1298, 1049, 33], [1299, 1049, 33], [1300, 1049, 33], [1301, 1049, 33], [1302, 1049, 33], [1303, 1049, 33], [1304, 1048, 32], [1305, 1048, 32], [1306, 1048, 32], [1307, 1048, 32], [1308, 1048, 32], [1309, 1048, 32], [1310, 1049, 33], [1311, 1049, 33], [1312, 1049, 33], [1313, 1049, 33], [1314, 1048, 32], [1315, 1048, 32], [1316, 1048, 32], [1317, 1048, 32], [1318, 1048, 32], [1319, 1049, 33], [1320, 1048, 32], [1321, 1048, 32], [1322, 1048, 32], [1323, 1048, 32], [1324, 1048, 32], [1325, 1048, 32], [1326, 1048, 32], [1327, 1048, 32], [1328, 1048, 32], [1329, 1048, 32], [1330, 1048, 32], [1331, 1048, 32], [1332, 1048, 32], [1333, 1048, 32], [1334, 1048, 32], [1335, 1048, 32], [1336, 1048, 32], [1337, 1048, 32], [1338, 1048, 32], [1339, 1048, 32], [1340, 1048, 32], [1341, 1048, 32], [1342, 1048, 32], [1343, 1048, 32], [1344, 1048, 32], [1345, 1048, 32], [1346, 1048, 32], [1347, 1048, 32], [1348, 1048, 32], [1349, 1048, 32], [1350, 1048, 32], [1351, 1048, 32], [1352, 1048, 32], [1353, 1048, 32], [1354, 1048, 32], [1355, 1048, 32], [1356, 1048, 32], [1357, 1048, 32], [1358, 1048, 32], [1359, 1048, 32], [1360, 1048, 32], [1361, 1048, 32], [1362, 1048, 32], [1363, 1048, 32], [1364, 1048, 32], [1365, 1048, 32], [1366, 1048, 32], [1367, 1048, 32], [1368, 1048, 32], [1369, 1048, 32], [1370, 1048, 32], [1371, 1048, 32], [1372, 1048, 32], [1373, 1048, 32], [1374, 1048, 32], [1375, 1048, 32], [1376, 1048, 32], [1377, 1048, 32], [1378, 1048, 32], [1379, 1048, 32], [1380, 1048, 32], [1381, 1047, 31], [1382, 1047, 31], [1383, 1047, 31], [1384, 1047, 31], [1385, 1047, 31], [1386, 1047, 31], [1387, 1047, 31], [1388, 1047, 31], [1389, 1047, 31], [1390, 1047, 31], [1391, 1047, 31], [1392, 1047, 31], [1393, 1047, 31], [1394, 1047, 31], [1395, 1047, 31], [1396, 1047, 31], [1397, 1047, 31], [1398, 1047, 31], [1399, 1047, 31], [1400, 1047, 31], [1401, 1047, 31], [1402, 1046, 30], [1403, 1046, 30], [1404, 1046, 30], [1405, 1046, 30], [1406, 1046, 30], [1407, 1046, 30], [1408, 1046, 30], [1409, 1046, 30], [1410, 1046, 30], [1411, 1046, 30], [1412, 1046, 30], [1413, 1046, 30], [1414, 1046, 30], [1415, 1046, 30], [1416, 1046, 30], [1417, 1046, 30], [1418, 1046, 30], [1419, 1046, 30], [1420, 1046, 30], [1421, 1046, 30], [1422, 1046, 30], [1423, 1046, 30], [1424, 1046, 30], [1425, 1046, 30], [1426, 1046, 30], [1427, 1046, 30], [1428, 1046, 30], [1429, 1046, 30], [1430, 1046, 30], [1431, 1046, 30], [1432, 1046, 30], [1433, 1046, 30], [1434, 1046, 30], [1435, 1046, 30], [1436, 1046, 30], [1437, 1046, 30], [1438, 1046, 30], [1439, 1046, 30], [1440, 1046, 30], [1441, 1046, 30], [1442, 1046, 30], [1443, 1046, 30], [1444, 1046, 30], [1445, 1046, 30], [1446, 1046, 30], [1447, 1046, 30], [1448, 1045, 29], [1449, 1045, 29], [1450, 1045, 29], [1451, 1045, 29], [1452, 1045, 29], [1453, 1045, 29], [1454, 1045, 29], [1455, 1045, 29], [1456, 1045, 29], [1457, 1045, 29], [1458, 1045, 29], [1459, 1045, 29], [1460, 1044, 28], [1461, 1045, 29], [1462, 1045, 29], [1463, 1045, 29], [1464, 1045, 29], [1465, 1045, 29], [1466, 1045, 29], [1467, 1045, 29], [1468, 1045, 29], [1469, 1045, 29], [1470, 1045, 29], [1471, 1045, 29], [1472, 1044, 28], [1473, 1044, 28], [1474, 1044, 28], [1475, 1044, 28], [1476, 1044, 28], [1477, 1044, 28], [1478, 1044, 28], [1479, 1044, 28], [1480, 1044, 28], [1481, 1044, 28], [1482, 1044, 28], [1483, 1044, 28], [1484, 1044, 28], [1485, 1044, 28], [1486, 1044, 28], [1487, 1044, 28], [1488, 1044, 28], [1489, 1044, 28], [1490, 1044, 28], [1491, 1044, 28], [1492, 1044, 28], [1493, 1044, 28], [1494, 1044, 28], [1495, 1044, 28], [1496, 1044, 28], [1497, 1044, 28], [1498, 1044, 28], [1499, 1044, 28], [1500, 1044, 28], [1501, 1044, 28], [1502, 1044, 28], [1503, 1044, 28], [1504, 1043, 27], [1505, 1043, 27], [1506, 1043, 27], [1507, 1043, 27], [1508, 1043, 27], [1509, 1043, 27], [1510, 1043, 27], [1511, 1043, 27], [1512, 1042, 26], [1513, 1042, 26], [1514, 1042, 26], [1515, 1042, 26], [1516, 1042, 26], [1517, 1042, 26], [1518, 1042, 26], [1519, 1042, 26], [1520, 1043, 27], [1521, 1042, 26], [1522, 1042, 26], [1523, 1042, 26], [1524, 1043, 27], [1525, 1043, 27], [1526, 1042, 26], [1527, 1042, 26], [1528, 1042, 26], [1529, 1042, 26], [1530, 1042, 26], [1531, 1042, 26], [1532, 1042, 26], [1533, 1042, 26], [1534, 1042, 26], [1535, 1042, 26], [1536, 1042, 26], [1537, 1042, 26], [1538, 1042, 26], [1539, 1042, 26], [1540, 1042, 26], [1541, 1042, 26], [1542, 1042, 26], [1543, 1042, 26], [1544, 1042, 26], [1545, 1042, 26], [1546, 1042, 26], [1547, 1041, 25], [1548, 1042, 26], [1549, 1042, 26], [1550, 1042, 26], [1551, 1042, 26], [1552, 1041, 25], [1553, 1041, 25], [1559, 1016, 0], [1560, 1016, 0], [1561, 1016, 0], [1562, 1016, 0], [1563, 1016, 0], [1564, 1016, 0], [1565, 1016, 0], [1566, 1016, 0], [1567, 1016, 0], [1568, 1016, 0], [1569, 1016, 0], [1570, 1016, 0], [1571, 1016, 0], [1572, 1016, 0], [1573, 1016, 0], [1574, 1016, 0], [1575, 1016, 0], [1576, 1016, 0], [1577, 1016, 0], [1578, 1016, 0], [1579, 1016, 0], [1580, 1016, 0], [1581, 1016, 0], [1582, 1016, 0], [1583, 1017, 1], [1584, 1016, 0], [1585, 1016, 0], [1586, 1016, 0], [1587, 1017, 1], [1588, 1017, 1], [1589, 1017, 1], [1590, 1016, 0], [1591, 1016, 0], [1592, 1016, 0], [1593, 1017, 1], [1594, 1017, 1], [1595, 1017, 1], [1596, 1017, 1], [1597, 1016, 0], [1598, 1016, 0], [1599, 1016, 0], [1600, 1016, 0], [1601, 1017, 1], [1602, 1016, 0], [1603, 1017, 1], [1604, 1017, 1], [1605, 1017, 1], [1606, 1017, 1], [1607, 1017, 1], [1608, 1016, 0], [1609, 1016, 0], [1610, 1016, 0], [1611, 1016, 0], [1612, 1016, 0], [1613, 1016, 0], [1614, 1016, 0], [1615, 1016, 0], [1616, 1016, 0], [1617, 1016, 0], [1618, 1016, 0], [1619, 1016, 0], [1620, 1016, 0], [1621, 1017, 1], [1622, 1017, 1], [1623, 1017, 1], [1624, 1017, 1], [1625, 1017, 1], [1626, 1017, 1], [1627, 1017, 1], [1628, 1017, 1], [1629, 1017, 1], [1630, 1017, 1], [1631, 1017, 1], [1632, 1017, 1], [1633, 1017, 1], [1634, 1017, 1], [1635, 1017, 1], [1636, 1016, 0], [1637, 1016, 0], [1638, 1016, 0], [1639, 1016, 0], [1640, 1016, 0], [1641, 1016, 0], [1642, 1017, 1], [1643, 1017, 1], [1644, 1017, 1], [1645, 1017, 1], [1646, 1017, 1], [1647, 1017, 1], [1648, 1017, 1], [1649, 1017, 1], [1650, 1017, 1], [1651, 1017, 1], [1652, 1017, 1], [1653, 1017, 1], [1654, 1017, 1], [1655, 1017, 1], [1656, 1017, 1], [1657, 1017, 1], [1658, 1017, 1], [1659, 1017, 1], [1660, 1017, 1], [1661, 1017, 1], [1662, 1017, 1], [1663, 1017, 1], [1664, 1017, 1], [1665, 1017, 1], [1666, 1017, 1], [1667, 1017, 1], [1668, 1017, 1], [1669, 1017, 1], [1670, 1017, 1], [1671, 1016, 0], [1672, 1017, 1], [1673, 1017, 1], [1674, 1017, 1], [1675, 1017, 1], [1676, 1017, 1], [1677, 1017, 1], [1678, 1016, 0], [1679, 1016, 0], [1680, 1017, 1], [1681, 1017, 1], [1682, 1017, 1], [1683, 1017, 1], [1684, 1017, 1], [1685, 1017, 1], [1686, 1017, 1], [1687, 1017, 1], [1688, 1016, 0], [1689, 1016, 0], [1690, 1016, 0], [1691, 1017, 1], [1692, 1016, 0], [1693, 1016, 0], [1694, 1016, 0], [1695, 1016, 0], [1696, 1017, 1], [1697, 1017, 1], [1698, 1017, 1], [1699, 1017, 1], [1700, 1017, 1], [1701, 1017, 1], [1702, 1017, 1], [1703, 1017, 1], [1704, 1017, 1], [1705, 1017, 1], [1706, 1017, 1], [1707, 1017, 1], [1708, 1017, 1], [1709, 1017, 1], [1710, 1017, 1], [1711, 1017, 1], [1712, 1017, 1], [1713, 1017, 1], [1714, 1017, 1], [1715, 1017, 1], [1716, 1017, 1], [1717, 1017, 1], [1718, 1017, 1], [1719, 1017, 1], [1720, 1017, 1], [1721, 1017, 1], [1722, 1017, 1], [1723, 1017, 1], [1724, 1017, 1], [1725, 1017, 1], [1726, 1017, 1], [1727, 1017, 1], [1728, 1017, 1], [1729, 1017, 1], [1730, 1017, 1], [1731, 1017, 1], [1732, 1017, 1], [1733, 1017, 1], [1734, 1017, 1], [1735, 1017, 1], [1736, 1017, 1], [1737, 1017, 1], [1738, 1017, 1], [1739, 1017, 1], [1740, 1017, 1], [1741, 1017, 1], [1742, 1017, 1], [1743, 1017, 1], [1744, 1017, 1], [1745, 1017, 1], [1746, 1017, 1], [1747, 1017, 1], [1748, 1017, 1], [1749, 1017, 1], [1750, 1017, 1], [1751, 1017, 1], [1752, 1017, 1], [1753, 1017, 1], [1754, 1017, 1], [1755, 1017, 1], [1756, 1017, 1], [1757, 1017, 1], [1758, 1017, 1], [1759, 1017, 1], [1760, 1017, 1], [1761, 1017, 1], [1762, 1017, 1], [1763, 1017, 1], [1764, 1017, 1], [1765, 1017, 1], [1766, 1017, 1], [1767, 1017, 1], [1768, 1017, 1], [1769, 1017, 1], [1770, 1017, 1], [1771, 1017, 1], [1772, 1017, 1], [1773, 1017, 1], [1774, 1017, 1], [1775, 1017, 1], [1776, 1017, 1], [1777, 1017, 1], [1778, 1017, 1], [1779, 1017, 1], [1780, 1017, 1], [1781, 1017, 1], [1782, 1017, 1], [1783, 1017, 1], [1784, 1017, 1], [1785, 1017, 1], [1786, 1017, 1], [1787, 1017, 1], [1788, 1017, 1], [1789, 1017, 1], [1790, 1017, 1], [1791, 1017, 1], [1792, 1017, 1], [1793, 1017, 1], [1794, 1017, 1], [1795, 1017, 1], [1796, 1017, 1], [1797, 1017, 1], [1798, 1017, 1], [1799, 1017, 1], [1800, 1017, 1], [1801, 1017, 1], [1802, 1017, 1], [1803, 1017, 1], [1804, 1017, 1], [1805, 1017, 1], [1806, 1017, 1], [1807, 1017, 1], [1808, 1017, 1], [1809, 1017, 1], [1810, 1017, 1], [1811, 1016, 0], [1812, 1016, 0], [1815, 1022, 6], [1819, 1023, 7], [1821, 1023, 7], [1822, 1021, 5], [1823, 1021, 5], [1824, 1022, 6], [1825, 1022, 6], [1826, 1022, 6], [1827, 1022, 6], [1828, 1022, 6], [1829, 1022, 6], [1830, 1022, 6], [1831, 1022, 6], [1833, 1023, 7], [1836, 1020, 4], [1870, 1054, 38], [1871, 1054, 38], [1872, 1055, 39], [1873, 1055, 39], [1874, 1055, 39], [1875, 1055, 39], [1876, 1055, 39], [1884, 1062, 46], [1885, 1062, 46], [1886, 1062, 46], [1887, 1063, 47], [1888, 1063, 47], [1889, 1063, 47], [1890, 1064, 48], [1891, 1064, 48], [1892, 1064, 48], [1893, 1064, 48], [1894, 1064, 48], [1895, 1064, 48], [1896, 1064, 48], [1897, 1064, 48], [1898, 1064, 48], [1899, 1064, 48], [1900, 1064, 48], [1901, 1064, 48], [1902, 1064, 48], [1903, 1064, 48], [1904, 1064, 48], [1905, 1058, 42], [1906, 1058, 42], [1907, 1058, 42], [1908, 1058, 42], [1909, 1058, 42], [1910, 1059, 43], [1911, 1059, 43], [1912, 1060, 44], [1913, 1060, 44], [1914, 1063, 47], [1915, 1063, 47], [1916, 1063, 47], [1917, 1063, 47], [1918, 1064, 48], [1919, 1064, 48], [1920, 1064, 48], [1921, 1064, 48], [1922, 1064, 48], [1923, 1064, 48], [1924, 1064, 48], [1925, 1064, 48], [1926, 1064, 48], [1927, 1064, 48], [1928, 1064, 48], [1929, 1064, 48], [1930, 1064, 48], [1931, 1064, 48], [1932, 1064, 48]]

# 将点数据转换为NumPy数组
points = np.array(point_data)

# 创建一个点云对象
pcd = o3d.geometry.PointCloud()

# 将NumPy数组中的点数据设置为点云的点
pcd.points = o3d.utility.Vector3dVector(points)

# 可视化点云
o3d.visualization.draw_geometries([pcd])

# 如果需要，可以将点云保存为PCD文件
o3d.io.write_point_cloud("output.pcd", pcd)


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 


True

In [ ]:
import cv2
import numpy as np
image = cv2.imread('diff_image.jpg')
for i in range(image.shape[0]): #行数
    image[i][1016] = [255,255,255]

cv2.imshow('image', image)
cv2.waitKey(0)

[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 255 255]
[255 2

-1

In [4]:
q =[1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1026, 1026, 1025, 1025, 1026, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1025, 1024, 1024, 1024, 1024, 1025, 1025, 1025, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1023, 1024, 1024, 1024, 1024, 1024, 1024, 1023, 1023, 1024, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1023, 1022, 1022, 1022, 1022, 1022, 1023, 1023, 1023, 1023, 1028, 1028, 1028, 1028, 1028, 1028, 1028, 1028, 1028, 1028, 1028, 1029, 1029, 1031, 1031, 1031, 1030, 1031, 1031, 1033, 1033, 1034, 1035, 1035, 1035, 1035, 1035, 1035, 1036, 1036, 1036, 1042, 1042, 1042, 1042, 1052, 1052, 1052, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1052, 1052, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1050, 1050, 1051, 1051, 1051, 1052, 1051, 1051, 1051, 1051, 1050, 1050, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1052, 1052, 1052, 1050, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1051, 1050, 1050, 1050, 1050, 1050, 1050,]
q =set(q)
q = list(q)
print(q)

[1024, 1025, 1026, 1028, 1029, 1030, 1031, 1064, 1033, 1034, 1035, 1036, 1042, 1050, 1051, 1052, 1022, 1023]


In [5]:
# 找基准线
import cv2
import numpy as np
import open3d as o3d
# 点云列表
point_data =[]
de =[]
dem =[]
n =100
for j in range(455,459):
    i_  = j*1000
    imageN = cv2.imread('./cap_v2/{}_diffN.bmp'.format(i_))
    imageP = cv2.imread('./cap_v2/{}_diffP.bmp'.format(i_)) 
    #print(j)
    diff = cv2.subtract(imageP, imageN)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY) # 转换为灰度图像  #0是黑色，255是白色
    m =[]
    for i in range(gray.shape[0]): #行数
        # 找到每一行最大亮度的索引
        #print(np.argmax(gray[i]),np.max(gray[i]))
        if np.max(gray[i])>20:  #10可以 5可以
            # 将最大值像素 置为255
            gray[i][np.argmax(gray[i])]=255
            # 其余的像素置为0
            gray[i][:np.argmax(gray[i])]=0
            gray[i][np.argmax(gray[i])+1:]=0
            m.append(np.argmax(gray[i]))
        else:
            # 其余的像素置为0
            gray[i][:]=0
    baseline = j
    d =[]
    print(j,m)
    print(min(m)) #这里为1096

    for i in range(gray.shape[0]): #行数
        if np.max(gray[i]) != 0:
            deep =np.argmax(gray[i])- 1096#1096
            #deep = min(max(np.argmax(gray[i])-1096,0),60) # 保持在-100到100之间
            if -4 <=(deep)<=70: #高度
                point_data.append([i,np.argmax(gray[i])-baseline,deep ])
                d.append(deep)
        gray[i][min(m)]=255 #显示用

    #print(d)
#     de.append(min(d))
#     dem.append(max(d))
# print(de)
# print(dem)
# print(min(de),max(dem))


print(point_data)
# 将点数据转换为NumPy数组
points = np.array(point_data)
# 创建一个点云对象
pcd = o3d.geometry.PointCloud()
# 将NumPy数组中的点数据设置为点云的点
pcd.points = o3d.utility.Vector3dVector(points)
# 可视化点云
#显示坐标轴
#coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=[0, 0, 0]) #x红 y绿 z蓝
o3d.visualization.draw_geometries([pcd])
# 如果需要，可以将点云保存为PCD文件
o3d.io.write_point_cloud("output_{}.pcd".format(n), pcd)

455 [1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1330, 1329, 1330, 1329, 1330, 1329, 1330, 1330, 1330, 1329, 1330, 1330, 1330, 1329, 1329, 1329, 1329, 1329, 1329, 1329, 1329, 1329, 1329,

RuntimeError: 

In [8]:
import cv2
import numpy as np
import open3d as o3d
# 点云列表
point_data =[]
de =[]
dem =[]
n =751
for j in range(n):
    i_  = j*1000
    imageN = cv2.imread('./cap_v2/{}_diffN.bmp'.format(i_))
    imageP = cv2.imread('./cap_v2/{}_diffP.bmp'.format(i_)) 
    print(j)
    diff = cv2.subtract(imageP, imageN)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY) # 转换为灰度图像  #0是黑色，255是白色
    m =[]
    for i in range(gray.shape[0]): #行数
        # 找到每一行最大亮度的索引
        #print(np.argmax(gray[i]),np.max(gray[i]))
        # if np.max(gray[i])>5:  #10可以 5可以
            # 将最大值像素 置为255
        gray[i][np.argmax(gray[i])]=255
        # 其余的像素置为0
        gray[i][:np.argmax(gray[i])]=0
        gray[i][np.argmax(gray[i])+1:]=0
        m.append(np.argmax(gray[i]))
        # else:
        #     # 其余的像素置为0
        #     gray[i][:]=0
    baseline = j
    d =[]
    #print(min(m)) #这里为1096
    for i in range(gray.shape[0]): #行数
        if np.max(gray[i]) != 0:
            deep =np.argmax(gray[i])- 1312#1096#1096
            #deep = min(max(np.argmax(gray[i])-1096,0),60) # 保持在-100到100之间
            if -4 <=(deep)<=70: #高度
                point_data.append([i,np.argmax(gray[i])-baseline,deep ])
                d.append(deep)
        gray[i][min(m)]=255 #显示用
    #print(d)
#     de.append(min(d))
#     dem.append(max(d))
# print(de)
# print(dem)
# print(min(de),max(dem))


#print(point_data)
# 将点数据转换为NumPy数组
points = np.array(point_data)
# 创建一个点云对象
pcd = o3d.geometry.PointCloud()
# 将NumPy数组中的点数据设置为点云的点
pcd.points = o3d.utility.Vector3dVector(points)
# 可视化点云
#显示坐标轴
#coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=[0, 0, 0]) #x红 y绿 z蓝
o3d.visualization.draw_geometries([pcd])
# 如果需要，可以将点云保存为PCD文件
o3d.io.write_point_cloud("output_v2_{}.pcd".format(n), pcd)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

True

In [2]:
import open3d as o3d
n =751
pcd = o3d.io.read_point_cloud("output_V2_{}.pcd".format(n))
o3d.visualization.draw_geometries([pcd])
pcd = o3d.io.read_point_cloud("output_v2_50-600_z_.pcd")
o3d.visualization.draw_geometries([pcd])

In [18]:
## 离群点移除
import open3d as o3d
n =1000
pcd = o3d.io.read_point_cloud("output_{}.pcd".format(n))
o3d.visualization.draw_geometries([pcd])


# # # 读取点云数据
# # pcd = o3d.io.read_point_cloud("path_to_your_point_cloud.pcd")

# 使用统计式离群点移除
cl, ind = pcd.remove_statistical_outlier(nb_neighbors=50, std_ratio=5) # 50个点，标准差5
inlier_cloud = pcd.select_by_index(ind) # 选择内点
outlier_cloud = pcd.select_by_index(ind, invert=True) # 选择离群点

inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])  # 灰色表示内点
outlier_cloud.paint_uniform_color([1, 0, 0])       # 红色表示离群点
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])
o3d.io.write_point_cloud("output_{}_统计式离群点移除_.pcd".format(n), inlier_cloud)
print("离群点:",len(outlier_cloud.points))
print("内点:",len(inlier_cloud.points))

# 使用半径式离群点剔除
cl, ind = pcd.remove_radius_outlier(nb_points=50, radius=10) # 50个点，半径5
inlier_cloud = pcd.select_by_index(ind)
outlier_cloud = pcd.select_by_index(ind, invert=True)

inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])  # 灰色表示内点
outlier_cloud.paint_uniform_color([1, 0, 0])       # 红色表示离群点
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])
o3d.io.write_point_cloud("output_{}_半径式离群点移除_.pcd".format(n), inlier_cloud)
print("离群点:",len(outlier_cloud.points))
print("内点:",len(inlier_cloud.points))

# # 可视化结果
# inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])  # 灰色表示内点
# outlier_cloud.paint_uniform_color([1, 0, 0])       # 红色表示离群点
# o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])


离群点: 11402
内点: 1904507
离群点: 7664
内点: 1908245


In [5]:
# 体素下采样 
import open3d as o3d
import numpy as np
from scipy.optimize import curve_fit

voxel_size = 5 #0.01越小密度越大
radius = 500#0.5   #搜索半径
num_knn = 500 #搜索邻域点的个数 #越多
pcd = o3d.io.read_point_cloud("output_1000_统计式离群点移除_.pcd") # "flaw.pcd"
o3d.visualization.draw_geometries([pcd])
print(len(pcd.points))
pcd = pcd.voxel_down_sample(voxel_size) #下采样
o3d.visualization.draw_geometries([pcd])
print(len(pcd.points))

1904507
101141


In [3]:
# 曲率下采样 法向量空间下采样
import open3d as o3d
import numpy as np
olderr = np.seterr(all='ignore')


def vector_angle(x, y):
    lx = np.sqrt(x.dot(x))
    ly = (np.sum(y ** 2, axis=1)) ** 0.5
    cos_angle = np.sum(x * y, axis=1) / (lx * ly) 
    cos_angle = np.clip(cos_angle, -1, 1)  # 由于浮点数运算的精度问题，可能会出现略大于1或者略小于-1的情况
    angle = np.arccos(cos_angle)  # arccos计算出的角度是弧度制
    angle2 = np.degrees(angle)    # 阈值设置中用的是角度制，因此这里需要将弧度转换为角度 #[0,180]
    # 大于90 度的，被180度减去 
    angle2[angle2 > 90] = 180 - angle2[angle2 > 90] # [0,90]
    #print(angle2)
    return angle2


knn_num = 10     # 自定义参数值(邻域点数)
angle_thre = 30#30  # 自定义参数值(角度制度)
N = 5            # 自定义参数值(每N个点采样一次)
C = 10           # 自定义参数值(采样均匀性>N)

pcd = o3d.io.read_point_cloud("output_1000_统计式离群点移除_.pcd")
point = np.asarray(pcd.points)
point_size = point.shape[0] # 点的个数
tree = o3d.geometry.KDTreeFlann(pcd)  # 建立KD树索引 #KDTreeFlann表示快速最近邻搜索
o3d.geometry.PointCloud.estimate_normals(
    pcd, search_param=o3d.geometry.KDTreeSearchParamKNN(knn=knn_num))  # 计算法向量 #KDTreesearchParamKNN表示K近邻搜索
normal = np.asarray(pcd.normals) # 法向量
normal_angle = np.zeros(point_size)
for i in range(point_size):
    [_, idx, dis] = tree.search_knn_vector_3d(point[i], knn_num + 1) # 搜索knn_num个最近邻点 +1是因为包括自身
    current_normal = normal[i]
    knn_normal = normal[idx[1:]] #1:表示除了自身的其他点 #type为numpy.ndarray
    normal_angle[i] = np.mean(vector_angle(current_normal, knn_normal)) #
    #print(i,normal_angle[i])

point_high = point[np.where(normal_angle >= angle_thre)]  # 位于特征明显区域的点
point_low = point[np.where(normal_angle < angle_thre)]    # 位于特征不明显区域的点
pcd_high = o3d.geometry.PointCloud()
pcd_high.points = o3d.utility.Vector3dVector(point_high)
pcd_low = o3d.geometry.PointCloud()
pcd_low.points = o3d.utility.Vector3dVector(point_low)
#pcd_high_down = o3d.geometry.PointCloud.uniform_down_sample(pcd_high, N)  # 均匀采样特征明显区域
pcd_low_down = o3d.geometry.PointCloud.uniform_down_sample(pcd_low, C)    # 均匀采样特征不明显区域
pcd_finl = o3d.geometry.PointCloud()
pcd_finl.points = o3d.utility.Vector3dVector(np.concatenate((np.asarray(pcd_high.points),   #
                                                             np.asarray(pcd_low_down.points))))  # 拼接点云
finl_point_size = np.asarray(pcd_finl.points).shape[0]
pcd_finl.paint_uniform_color([0.8, 0.8, 0.8]) # 灰色
print("原始点云点的个数为：", point_size)
print("下采样后点的个数为：", finl_point_size)
o3d.visualization.draw_geometries([pcd_finl], window_name="曲率下采样",
                                  width=1024, height=768,
                                  left=50, top=50,
                                  mesh_show_back_face=False)







原始点云点的个数为： 1904507
下采样后点的个数为： 402461
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [29]:
c = np.array([1])
k = np.array([1,2,3,4,5,6,7,8,9,10])
def v(c,k):
    return c+k
print(np.mean(v(c, k)))


angle2 = np.array([18.29631221, 173.93620986, 173.93620986, 12.19965731, 2.98012549,
                   16.75371418, 151.39485994, 151.39485994, 168.98736931, 2.98012549])
angle2[angle2 > 90] = 180 - angle2[angle2 > 90]
print(angle2)

6.5
[18.29631221  6.06379014  6.06379014 12.19965731  2.98012549 16.75371418
 28.60514006 28.60514006 11.01263069  2.98012549]


In [7]:
import  numpy as np
gr =[1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1026, 1026, 1025, 1025, 1026]
gr = np.argmax(gr)
print(gr)
print(type(gr))
# 将1转换成numpy数组
print(type(np.int64(1)))

0
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
#线程
import cv2
import numpy as np
import open3d as o3d
import threading

# 点云处理函数
def process_point_cloud(start, end, point_data, lock):
    for j in range(start, end):
        i_ = j * 1000
        imageN = cv2.imread('./cap_v1/{}_diffN.bmp'.format(i_))
        imageP = cv2.imread('./cap_v1/{}_diffP.bmp'.format(i_))
        # ... 省略其他处理步骤 ...

        # 假设您已经得到了处理后的点数据
        processed_points = [...]  # 替换为实际的点数据处理结果

        # 使用锁来确保线程安全
        with lock:
            point_data.extend(processed_points)

# 主函数
def main():
    n = 1000
    num_threads = 10  # 可以根据您的系统能力调整线程数量
    point_data = []
    lock = threading.Lock()

    # 创建并启动线程
    threads = []
    for i in range(num_threads):
        start = i * (n // num_threads)
        end = (i + 1) * (n // num_threads) if i != num_threads - 1 else n
        thread = threading.Thread(target=process_point_cloud, args=(start, end, point_data, lock))
        threads.append(thread)
        thread.start()

    # 等待所有线程完成
    for thread in threads:
        thread.join()

    # 将点数据转换为NumPy数组
    points = np.array(point_data)
    # 创建一个点云对象
    pcd = o3d.geometry.PointCloud()
    # 将NumPy数组中的点数据设置为点云的点
    pcd.points = o3d.utility.Vector3dVector(points)
    # 可视化点云
    o3d.visualization.draw_geometries([pcd])
    # 如果需要，可以将点云保存为PCD文件
    o3d.io.write_point_cloud("output_{}.pcd".format(n), pcd)

if __name__ == "__main__":
    main()


In [2]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义高斯函数的参数
A = 1
x0 = 0
y0 = 0
sigma_X = 1
sigma_Y = 2

# 生成 X 和 Y 的坐标网格
X, Y = np.meshgrid(np.arange(-5, 5.1, 0.1), np.arange(-5, 5.1, 0.1))#-5到5，步长为0.1

# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()

# 循环旋转角度
for theta in np.arange(0, np.pi, np.pi / 100): # 0 到 π，步长为 π / 100  #可以改变这个值
    # 计算高斯函数的系数
    a = np.cos(theta) ** 2 / (2 * sigma_X ** 2) + np.sin(theta) ** 2 / (2 * sigma_Y ** 2)
    b = np.sin(2 * theta) / (4 * sigma_X ** 2) - np.sin(2 * theta) / (4 * sigma_Y ** 2)
    c = np.sin(theta) ** 2 / (2 * sigma_X ** 2) + np.cos(theta) ** 2 / (2 * sigma_Y ** 2)

    # 计算 Z 的坐标
    Z = A * np.exp(-(a * (X - x0) ** 2 + 2 * b * (X - x0) * (Y - y0) + c * (Y - y0) ** 2))

    # 将 X, Y, Z 合并为点云矩阵，形状为 (n, 3)
    points = np.stack((X, Y, Z), axis=-1)
    points = points.reshape(-1, 3)

# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)

# 添加坐标
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
o3d.visualization.draw_geometries([pcd, coord])



[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 不支持请求的转换操作。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] GLFW Error

In [3]:
import open3d as o3d
pcd = o3d.io.read_point_cloud("output_v2_751.pcd")
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: 句柄无效。 
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
