In [3]:
import open3d as o3d
import numpy as np
from scipy.optimize import curve_fit
voxel_size = 0.01 #越小密度越大
radius = 0.07
pcd = o3d.io.read_point_cloud("bunny.pcd")
pcd = pcd.voxel_down_sample(voxel_size) #下采样
cloud = pcd
num_points = len(cloud.points) #点云中点的个数
points = np.asarray(cloud.points) #点云转换为数组 点云数组形式为[[x1,y1,z1],[x2,y2,z2],...]
kdtree = o3d.geometry.KDTreeFlann(cloud) #建立KDTree
# 定义非线性函数，这里假设是一个二次曲面
def func(x, a, b, c, d, e, f):
    return a * x[0]**2 + b * x[1]**2 + c * x[0] * x[1] + d * x[0] + e * x[1] + f
def f(x, y):
    return popt[0]*x**2 +popt[1]*y**2 +popt[2]* x*y +popt[3]*x + popt[4]*y +popt[5]
for i in range(num_points):
    k, idx, _ = kdtree.search_radius_vector_3d(cloud.points[i], radius) #返回邻域点的个数和索引
    neighbors = points[idx] #数组形式为[[x1,y1,z1],[x2,y2,z2],...]
    #print(k)
    Y = neighbors[:, 2] # 因变量
    X = neighbors[:, [0,1]] # 自变量 [[2,3],[1,1],[8,9],[11,12],[4,5],[8,9]] 6*2
    popt, pcov = curve_fit(func, xdata=X.T,ydata= Y)
    print(f(1,1))



1.0153207018266084
15.741267152021983
16.288430234541266
-5.767673534497346
49.216096213924956
-14.085326741797548
-4.058578446448431
40.36648902059547
-1.6953127295372818
-14.688824573989475
0.37487033806427594
-5.702102918825492
-6.750377173064616
4.152267226093491
32.97166831006562
-6.503158693591439
-4.012168604660847
-2.5476578209195897
5.379411190863804
30.26164709944658
-1.382104030481688
7.380139645395506
47.227842557703646
39.210456325783305
-7.022327453305808
-8.247005992627086
-4.95139335909491
24.35108506444339
-5.854752790978981
-18.26228883345351
-12.4932141489752
4.27209058647022
-1.4829543772016447
43.15237812227394
24.504379858080007
0.12930387567860585
0.12113349807111476
-28.515497757138974
-9.137056234848947
-21.541301937101334
-8.393972339191627
-45.09721711019873
-19.52167004621422
-1.345569863427221
-34.298902768128116
2.9574634213051536
-12.005014239451206
-18.699869315592814
-23.710898691477723
-12.885611577833947
-1.4156913290341961
-1.328587343813825
5.455310

In [1]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义平面的参数，z = ax + by + d
plane_params = [0, 0, 1]

# 定义平面的范围，x 和 y 的最小值和最大值
x_min = -10
x_max = 10
y_min = -10
y_max = 10

# 定义点云的密度，每个单位长度有多少个点
density = 10

# 定义凹陷的半径和深度
radius = 1
depth = 1

# 生成 x 和 y 的坐标网格
x = np.linspace(x_min, x_max, int((x_max - x_min) * density))
y = np.linspace(y_min, y_max, int((y_max - y_min) * density))
x, y = np.meshgrid(x, y)

# 计算 z 的坐标，根据平面方程和凹陷函数
z = plane_params[0] * x + plane_params[1] * y + plane_params[2]
z -= depth * np.exp(-((x ** 2 + y ** 2) / radius ** 2)) #

# 添加随机噪声，范围为 +-0.5mm
noise = np.random.uniform(-0.5, 0.5, size=z.shape)
#z += noise

# 将 x, y, z 合并为点云矩阵，形状为 (n, 3)
points = np.stack((x, y, z), axis=-1)
points = points.reshape(-1, 3)

# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

# 可视化点云
# 添加坐标
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色

o3d.visualization.draw_geometries([pcd, coord])


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [16]:
import open3d as o3d
import numpy as np

pcd = o3d.io.read_point_cloud("bunny.pcd")
#显示点云
o3d.visualization.draw_geometries([pcd])

#https://zhuanlan.zhihu.com/p/82504804
#https://baike.baidu.com/item/%E4%BA%8C%E7%BB%B4%E6%AD%A3%E6%80%81%E5%88%86%E5%B8%83/2951835
#高斯函数


In [ ]:
import open3d as o3d
import numpy as np

#将ply转换成pcd
def convert_ply_to_pcd(ply_file, pcd_file):
    # 读取PLY文件
    point_cloud = o3d.io.read_point_cloud(ply_file)
 
    # 保存为PCD文件
    o3d.io.write_point_cloud(pcd_file, point_cloud)
 
# 使用示例
ply_file_path = r'bunny\reconstruction\bunny.ply'  #填入ply文件的路径
pcd_file_path = r'bunny.pcd'  #填入pcd文件的路径
convert_ply_to_pcd(ply_file_path, pcd_file_path)

In [30]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义高斯函数的参数
A = -1
x0 = 0
y0 = 0
sigma_X = 1
sigma_Y = 2

# 生成 X 和 Y 的坐标网格
X, Y = np.meshgrid(np.arange(-5, 5.1, 0.1), np.arange(-5, 5.1, 0.1))#-5到5，步长为0.1
noise = np.random.uniform(-0.5, 0.5, size=X.shape)
X += noise
Y += noise
# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()

# 循环旋转角度
for theta in np.arange(0, np.pi, np.pi / 100): # 0 到 π，步长为 π / 100  #可以改变这个值
    # 计算高斯函数的系数
    a = np.cos(theta) ** 2 / (2 * sigma_X ** 2) + np.sin(theta) ** 2 / (2 * sigma_Y ** 2)
    b = np.sin(2 * theta) / (4 * sigma_X ** 2) - np.sin(2 * theta) / (4 * sigma_Y ** 2)
    c = np.sin(theta) ** 2 / (2 * sigma_X ** 2) + np.cos(theta) ** 2 / (2 * sigma_Y ** 2)

    # 计算 Z 的坐标
    Z = A * np.exp(-(a * (X - x0) ** 2 + 2 * b * (X - x0) * (Y - y0) + c * (Y - y0) ** 2))

    # # 添加随机噪声，从一个均匀分布中生成随机样本 范围为 +-0.5mm 
    # noise = np.random.uniform(-0.5, 0.5, size=Z.shape)
    # Z += noise

    # 将 X, Y, Z 合并为点云矩阵，形状为 (n, 3)
    points = np.stack((X, Y, Z), axis=-1)
    points = points.reshape(-1, 3)

# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)

# 添加坐标
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
o3d.visualization.draw_geometries([pcd, coord])
# 保存点云
o3d.io.write_point_cloud("flaw.pcd",pcd ) 



[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


True

In [24]:
import open3d as o3d
import numpy as np

# 从PCD文件中读取点云
pcd = o3d.io.read_point_cloud("flaw.pcd")
c=np.asarray(pcd.points)
print(c)
print(c.shape)

[[-5.00000000e+00 -5.00000000e+00 -1.38879437e-11]
 [-4.90000010e+00 -5.00000000e+00 -2.27831469e-11]
 [-4.80000019e+00 -5.00000000e+00 -3.70038201e-11]
 ...
 [ 4.80000019e+00  5.00000000e+00 -3.70038201e-11]
 [ 4.90000010e+00  5.00000000e+00 -2.27831469e-11]
 [ 5.00000000e+00  5.00000000e+00 -1.38879437e-11]]
(10201, 3)


In [35]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义心形函数
def heart_function(t): 
    x = 16 * np.sin(t) ** 3
    y = 13 * np.cos(t) - 5 * np.cos(2 * t) - 2 * np.cos(3 * t) - np.cos(4 * t)
    return x, y

# 生成参数 t 的值
t = np.linspace(0, 2 * np.pi, 1000)#0到2π，1000个点

# 计算心形曲线的坐标
x, y = heart_function(t)

# 生成随机的 z 坐标
z = np.random.uniform(-1, 1, size=1000)

# 创建一个空的点云对象
pcd = o3d.geometry.PointCloud()

# 将坐标和颜色赋给点云对象
pcd.points = o3d.utility.Vector3dVector(np.c_[x, y, z])
pcd.colors = o3d.utility.Vector3dVector(np.c_[np.ones(1000), np.zeros(1000), np.zeros(1000)])

# 创建一个球体对象，作为心形的立体部分
sphere = o3d.geometry.TriangleMesh.create_sphere(radius=1.0)

# 将球体对象变换到心形的中心位置
sphere.translate((0, -2, 0))

# 将球体对象的颜色设置为红色
sphere.paint_uniform_color((1, 0, 0))

# # 将点云对象和球体对象合并为一个几何对象
# geo = o3d.geometry.Geometry3D()
# geo += pcd
# geo += sphere

# 绘制三维几何对象
o3d.visualization.draw_geometries([pcd, sphere])


In [ ]:
import open3d as o3d
import numpy as np
from scipy.optimize import curve_fit

# 定义平面的范围，x 和 y 的最小值和最大值
x_min = -10
x_max = 10
y_min = -10
y_max = 10

# 定义点云的密度，每个单位长度有多少个点
density = 10

# 生成 x 和 y 的坐标网格
x = np.linspace(x_min, x_max, int((x_max - x_min) * density))
y = np.linspace(y_min, y_max, int((y_max - y_min) * density))
x, y = np.meshgrid(x, y)

(x**2+9*y**2/4+z**2-1)**3-x**2*z**3-9*y**2*z**3/200=0

In [31]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义满足式子的函数
def f(x, y, z):
    return (x**2 + 32*y**2 + z**2 - 1)**3 - x**2*z**3 - 9*y**2*z**3/200

# 生成 x, y, z 的值
# 生成随机数
np.random.seed(0)
# 生成 x, y, z 的值
x = np.random.uniform(-1.2, 1.2, 200) # 
y = np.random.uniform(-0.7, 0.7, 200)
z = np.random.uniform(-0.98, 1.24, 200)
# x = np.linspace(-1.1, 1.1, 200)
# y = np.linspace(-0.7, 0.7, 200)
# z = np.linspace(-0.98, 1.24, 200)

# 创建一个空的点云列表
points = []

# 遍历 x, y, z 的值，找出满足式子的点
for i in x:
    for j in y:
        for k in z:
            # 如果 f(i, j, k) 接近于 0，说明该点满足式子
            if abs(f(i, j, k)) < 1e-4:
                # 将该点的坐标添加到点云列表中
                points.append([i, j, k])

# 将点云列表转换为 numpy 数组
points = np.array(points)


# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()
# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)
# 改变点云的颜色
pcd.paint_uniform_color([1, 0, 0])

# voxel_size = 0.2
# downpcd = pcd.voxel_down_sample(voxel_size)

# 坐标轴
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，
front = [0, 1, 0] # 相机的前方向，
zoom = 1 # 相机的缩放比例，
o3d.visualization.draw_geometries([pcd], window_name='Point Cloud', width=800, height=600,lookat=lookat, up=up, front=front, zoom=zoom)


# 保存点云
o3d.io.write_point_cloud("heart.pcd", pcd)




[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


True

In [70]:
x = np.linspace(-1, 0, 100)+np.random.uniform(0, 1, 100)
print(x)
y = np.linspace(-1, 0, 100)
print(y)


[-0.40711973 -0.97983529 -0.50397178 -0.26092658 -0.91562053 -0.06997347
 -0.41931252 -0.89863188 -0.69477831  0.04458479 -0.31667017 -0.78141632
 -0.59124338 -0.41198324 -0.83763579 -0.43686933 -0.3489252  -0.58460495
 -0.22954282 -0.05484069 -0.56214557 -0.16737889 -0.13815553  0.18086353
  0.02070041  0.10087052 -0.24695383 -0.54192414  0.27864358 -0.57771495
 -0.22551238 -0.61877559  0.26708318  0.29825827  0.06282341 -0.2964718
 -0.38198124 -0.3609593  -0.48886759 -0.08025165 -0.45414232 -0.26912792
  0.0509489   0.16188704 -0.53128285 -0.11533856  0.11677106  0.32799345
 -0.03982673  0.46415537 -0.22931695 -0.47133978  0.00900539 -0.20853267
  0.36917222 -0.21167177 -0.12371422  0.36698501  0.30100184  0.15401083
  0.31100867  0.03479848 -0.36842733 -0.35228124  0.15768643 -0.26014336
 -0.28225785  0.64228432  0.54587133 -0.15100308 -0.29226507  0.65883951
  0.00559803 -0.07672866  0.43898286 -0.1335205   0.03232637  0.75287246
  0.42734156  0.31865759  0.20599942  0.59268277 -0.

In [71]:
# 导入 open3d 库
import open3d as o3d

# 读取一个点云文件
pcd = o3d.io.read_point_cloud("heart.pcd")
cloud = pcd
points = np.asarray(cloud.points) #点云转换为数组

# # 估计点云的法向量
# pcd.estimate_normals()
# # 设置球的半径
# radii = [0.005, 0.01, 0.02, 0.04]
# # 调用 o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting 函数
# mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, o3d.utility.DoubleVector(radii))

# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，设为 y 轴正方向
front = [0, 1, 0] # 相机的前方向，设为 z 轴负方向
zoom = 1 # 相机的缩放比例，设为 0.5
# 坐标轴
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 调用 o3d.visualization.draw_geometries 函数，并传入视角的参数
o3d.visualization.draw_geometries([pcd,coord], window_name='Point Cloud', width=800, height=600,lookat=lookat, up=up, front=front, zoom=zoom)


In [75]:
# 导入 open3d 库
import open3d as o3d

# 读取一个点云文件
pcd = o3d.io.read_point_cloud("heart.pcd")

# 估计点云的法向量
pcd.estimate_normals()

# 设置球的半径
radii = [0.005, 0.01, 0.02, 0.04]

# 调用 o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting 函数
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, o3d.utility.DoubleVector(radii))

# 绘制点云和三角网格
o3d.visualization.draw_geometries([pcd, mesh])


In [65]:
# 导入 open3d 库
import open3d as o3d

# 读取一个点云文件
pcd = o3d.io.read_point_cloud("heart.pcd")
cloud = pcd
points = np.asarray(cloud.points) #点云转换为数组
print(points[0])
print(len(points))
print(points[:,0].max())
print(points[:,0].min())
print(points[:,1].max())
print(points[:,1].min())
print(points[:,2].max())
print(points[:,2].min())
print(points)

[ 0.10738971 -0.6654498   0.02824052]
12479
1.0744224786758423
-1.089669942855835
0.6684932112693787
-0.6710885763168335
1.194549798965454
-0.9624972939491272
[[ 0.10738971 -0.6654498   0.02824052]
 [ 0.10738971 -0.6654498  -0.0280735 ]
 [ 0.10738971 -0.6654498  -0.03852244]
 ...
 [-0.14428343 -0.65337354  0.00131912]
 [-0.14428343 -0.65337354  0.0109956 ]
 [-0.14428343 -0.65337354 -0.00261447]]


In [82]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("heart.pcd")
print(pcd)

print("->正在可视化原始点云")
o3d.visualization.draw_geometries([pcd])

print("->正在体素下采样...")
voxel_size = 0.2
downpcd = pcd.voxel_down_sample(voxel_size)
print(downpcd)

# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，设为 y 轴正方向
front = [0, 1, 0] # 相机的前方向，设为 z 轴负方向
zoom = 1 # 相机的缩放比例，设为 0.5
# 坐标轴
#coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 调用 o3d.visualization.draw_geometries 函数，并传入视角的参数
o3d.visualization.draw_geometries([downpcd], window_name='Point Cloud', width=800, height=600,lookat=lookat, up=up, front=front, zoom=zoom)


->正在加载点云... 
PointCloud with 47166 points.
->正在可视化原始点云
->正在体素下采样...
PointCloud with 356 points.


In [7]:
import sympy

x, y,z = sympy.symbols("x, y, z")
s = sympy.solve((x**2 + 9*y**2/4 + z**2 - 1)**3 - x**2*z**3 - 9*y**2*z**3/200)
print(s)
print(len(s))
print(s[0])
print(s[1])
print(s[2])
print(s[3])
print(s[4])
print(s[5])

[{x: -5**(1/6)*sqrt(6)*sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*sqrt(3)*sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*sqrt(3)*sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) + 120*5**(2/3))/60}, {x: 5**(1/6)*sqrt(6)*sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*sqrt(3)*sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*sqrt(3)*sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(

In [10]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义满足式子的函数
def f(x, y, z):
    return (x**2 + 9*y**2/4 + z**2 - 1)**3 - x**2*z**3 - 9*y**2*z**3/200

def f1(y,z):
    return -5**(1/6)*np.sqrt(6)*np.sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3 
    + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) + 120*5**(2/3))/60

# 生成 x, y, z 的值
# 生成随机数
np.random.seed(0)
# 生成 x, y, z 的值
y = np.random.uniform(-2,2, 100) # 
z = np.random.uniform(-2,2, 100)
x = f1(y,z)

# 将 X, Y, Z 合并为点云矩阵，形状为 (n, 3)
points = np.stack((x, y, z), axis=-1)
points = points.reshape(-1, 3)



# 将点云列表转换为 numpy 数组
points = np.array(points)


# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()
# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)
# 改变点云的颜色
pcd.paint_uniform_color([1, 0, 0])

# voxel_size = 0.2
# downpcd = pcd.voxel_down_sample(voxel_size)

# 坐标轴
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，
front = [0, 1, 0] # 相机的前方向，
zoom = 1 # 相机的缩放比例，
o3d.visualization.draw_geometries([pcd,coord], window_name='Point Cloud',lookat=lookat, up=up, front=front, zoom=zoom)


# 保存点云
o3d.io.write_point_cloud("heart.pcd", pcd)

C:\Users\REM\AppData\Local\Temp\ipykernel_22988\2287850633.py:11: RuntimeWarning: invalid value encountered in sqrt
  + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) + 120*5**(2/3))/60
C:\Users\REM\AppData\Local\Temp\ipykernel_22988\2287850633.py:10: RuntimeWarning: invalid value encountered in power
  return -5**(1/6)*np.sqrt(6)*np.sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3
C:\Users\REM\AppData\Local\Temp\ipykernel_22988\2287850633.py:11: RuntimeWarning: invalid value encountered in power
  + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 +

True

In [18]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

def f1(y,z):
    return -5**(1/6)*np.sqrt(6)*np.sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3 
    + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) + 120*5**(2/3))/60

# 生成随机数
np.random.seed(0)
# 生成 x, y, z 的值
y = np.random.uniform(-0.1,0.1, 200) # 
z = np.random.uniform(-0.1,0.1, 200)
x = f1(y,z)
# 找出x中为nan的索引
index = np.argwhere(np.isnan(x))
# 删除x中的nan
x = np.delete(x,index)
y = np.delete(y,index)
z = np.delete(z,index)
# 将 X, Y, Z 合并为点云矩阵，形状为 (n, 3)
points = np.stack((x, y, z), axis=-1)
points = points.reshape(-1, 3)
# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()
# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)
# 改变点云的颜色
pcd.paint_uniform_color([1, 0, 0])

# 坐标轴
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，
front = [0, 1, 0] # 相机的前方向，
zoom = 1 # 相机的缩放比例，
o3d.visualization.draw_geometries([pcd,coord], window_name='Point Cloud',lookat=lookat, up=up, front=front, zoom=zoom)


C:\Users\REM\AppData\Local\Temp\ipykernel_26264\500851460.py:6: RuntimeWarning: invalid value encountered in power
  return -5**(1/6)*np.sqrt(6)*np.sqrt(-270*5**(2/3)*y**2 - 4000*2**(1/3)*3**(2/3)*z**3/(793800*y**2*z**3
C:\Users\REM\AppData\Local\Temp\ipykernel_26264\500851460.py:7: RuntimeWarning: invalid value encountered in power
  + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) - 120*5**(2/3)*z**2 - 60**(1/3)*(793800*y**2*z**3 + 360000*z**5 - 360000*z**3 + 200*np.sqrt(3)*np.sqrt(5250987*y**4*z**6 + 4762800*y**2*z**8 - 4762800*y**2*z**6 + 1080000*z**10 - 160000*z**9 - 2160000*z**8 + 1080000*z**6))**(1/3) + 120*5**(2/3))/60


In [20]:
# 导入 numpy 和 open3d 库
import numpy as np
import open3d as o3d

# 定义参数范围
t = np.linspace(0, np.pi, 100)
phi = np.linspace(0, 2*np.pi, 100)

# 创建网格
t, phi = np.meshgrid(t, phi)

# 计算坐标
x = 16/81 * np.sin(t)**3 * np.cos(phi)**3
y = 16/81 * np.sin(t)**3 * np.sin(phi)**3
z = 4/9 * np.sin(t)**3


# 将 X, Y, Z 合并为点云矩阵，形状为 (n, 3)
points = np.stack((x, y, z), axis=-1)
points = points.reshape(-1, 3)
# 创建 open3d 点云对象
pcd = o3d.geometry.PointCloud()
# 更新点云的坐标
pcd.points = o3d.utility.Vector3dVector(points)
# 改变点云的颜色
pcd.paint_uniform_color([1, 0, 0])

# 坐标轴
coord = o3d.geometry.TriangleMesh.create_coordinate_frame(size=1, origin=[0, 0, 0])#x红色，y绿色，z蓝色
# 可视化点云
# 设置视角的参数
lookat = [0, 0, 0] # 相机的观察点，设为原点
up = [0, 0, 1] # 相机的上方向，
front = [0, 1, 0] # 相机的前方向，
zoom = 1 # 相机的缩放比例，
o3d.visualization.draw_geometries([pcd,coord], window_name='Point Cloud',lookat=lookat, up=up, front=front, zoom=zoom)