In [ ]:
import open3d as o3d

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

# 法线估计
radius = 0.01   # 搜索半径
max_nn = 30     # 邻域内用于估算法线的最大点数
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius, max_nn))     # 执行法线估计

# 可视化
o3d.visualization.draw_geometries([pcd], 
                                  window_name = "可视化参数设置",
                                  width = 600,
                                  height = 450,
                                  left = 30,
                                  top = 30,
                                  point_show_normal = True)


In [ ]:
import open3d as o3d
import numpy as np


print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

# 将点云设置为灰色
pcd.paint_uniform_color([0.5, 0.5, 0.5])

# 建立KDTree
pcd_tree = o3d.geometry.KDTreeFlann(pcd)

# 将第1500个点设置为紫色
pcd.colors[1500] = [0.5, 0, 0.5]

# 使用K近邻，将第1500个点最近的5000个点设置为蓝色
print("使用K近邻，将第1500个点最近的5000个点设置为蓝色")
k = 5000    # 设置K的大小
[num_k, idx_k, _] = pcd_tree.search_knn_vector_3d(pcd.points[1500], k)    # 返回邻域点的个数和索引
np.asarray(pcd.colors)[idx_k[1:], :] = [0, 0, 1]  # 跳过最近邻点（查询点本身）进行赋色
print("k邻域内的点数为：", num_k)

# 使用半径R近邻，将第1500个点半径（0.02）范围内的点设置为红色
print("使用半径R近邻，将第1500个点半径（0.02）范围内的点设置为红色")
radius = 0.02   # 设置半径大小
[num_radius, idx_radius, _] = pcd_tree.search_radius_vector_3d(pcd.points[1500], radius)   # 返回邻域点的个数和索引
np.asarray(pcd.colors)[idx_radius[1:], :] = [1, 0, 0]  # 跳过最近邻点（查询点本身）进行赋色
print("半径r邻域内的点数为：", num_radius)

# 使用混合邻域，将半径R邻域内不超过max_num个点设置为绿色
print("使用混合邻域，将第1500个点半径R邻域内不超过max_num个点设置为绿色")
max_nn = 200   # 半径R邻域内最大点数
[num_hybrid, idx_hybrid, _] = pcd_tree.search_hybrid_vector_3d(pcd.points[1500], radius, max_nn)
np.asarray(pcd.colors)[idx_hybrid[1:], :] = [0, 1, 0]  # 跳过最近邻点（查询点本身）进行赋色
print("混合邻域内的点数为：", num_hybrid)

print("->正在可视化点云...")
o3d.visualization.draw_geometries([pcd])


In [ ]:
li=[1,2,3,4,5,6,7,8,9,10]
li[1:]

In [ ]:
import open3d as o3d
import numpy as np

print("Load a ply point cloud, print it, and render it")
sample_ply_data = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(sample_ply_data.path)
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

In [ ]:
import open3d as o3d
import numpy as np

##############li =[1,2,3,4,5,6,7,8,9,10]
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

# 将点云设置为灰色
pcd.paint_uniform_color([0.5, 0.5, 0.5])

# 建立KDTree
pcd_tree = o3d.geometry.KDTreeFlann(pcd)

# 将第1500个点设置为紫色
pcd.colors[1500] = [0.5, 0, 0.5]
#############print(np.asarray(pcd.colors)[[li[1:]]])          np.asarray(pcd.colors)[idx_k[1:],:] 中,:可去
# 使用K近邻，将第1500个点最近的5000个点设置为蓝色
print("使用K近邻，将第1500个点最近的5000个点设置为蓝色")  
k = 5000    # 设置K的大小
[num_k, idx_k, _] = pcd_tree.search_knn_vector_3d(pcd.points[1500], k)    # 返回邻域点的个数和索引
np.asarray(pcd.colors)[idx_k[1:]] = [0, 0, 1]  # 跳过最近邻点（查询点本身）进行赋色
print("k邻域内的点数为：", num_k)

# 使用半径R近邻，将第1500个点半径（0.02）范围内的点设置为红色
print("使用半径R近邻，将第1500个点半径（0.02）范围内的点设置为红色")
radius = 0.02   # 设置半径大小
[num_radius, idx_radius, _] = pcd_tree.search_radius_vector_3d(pcd.points[1500], radius)   # 返回邻域点的个数和索引
np.asarray(pcd.colors)[idx_radius[1:]] = [1, 0, 0]  # 跳过最近邻点（查询点本身）进行赋色
print("半径r邻域内的点数为：", num_radius)

# 使用混合邻域，将半径R邻域内不超过max_num个点设置为绿色
print("使用混合邻域，将第1500个点半径R邻域内不超过max_num个点设置为绿色")
max_nn = 200   # 半径R邻域内最大点数
[num_hybrid, idx_hybrid, _] = pcd_tree.search_hybrid_vector_3d(pcd.points[1500], radius, max_nn)
np.asarray(pcd.colors)[idx_hybrid[1:]] = [0, 1, 0]  # 跳过最近邻点（查询点本身）进行赋色
print("混合邻域内的点数为：", num_hybrid)

print("->正在可视化点云...")
o3d.visualization.draw_geometries([pcd])

In [ ]:
import open3d as o3d
import numpy as np

# --------------------------- 加载点云 ---------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)
# ==============================================================

# ------------------------- 构建Octree --------------------------
print('octree 分割')
octree = o3d.geometry.Octree(max_depth=4)
octree.convert_from_point_cloud(pcd, size_expand=0.01)
print("->正在可视化Octree...")
o3d.visualization.draw_geometries([octree])
# ==============================================================


In [ ]:
import open3d as o3d
import numpy as np

# --------------------------- 加载点云 ---------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)
# ==============================================================

# ------------------------- 构建Octree --------------------------
print('体素化')
voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(pcd, voxel_size=0.01)
print("体素：", voxel_grid)
print("正在可视化体素...")
o3d.visualization.draw_geometries([voxel_grid])

print('Octree 分割')
octree = o3d.geometry.Octree(max_depth=4)  #八叉树的最大深度为4
octree.create_from_voxel_grid(voxel_grid)
print("Octree：", octree)
print("正在可视化Octree...")
o3d.visualization.draw_geometries([octree])
# ==============================================================


In [ ]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在可视化原始点云")
o3d.visualization.draw_geometries([pcd])

print("->正在体素下采样...")
voxel_size = 0.01 #越小密度越大
downpcd = pcd.voxel_down_sample(voxel_size)
print(downpcd)

print("->正在可视化下采样点云")
o3d.visualization.draw_geometries([downpcd])


In [ ]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)

# ------------------------- 统计滤波 --------------------------
print("->正在进行统计滤波...")
num_neighbors = 20 # K邻域点的个数
std_ratio = 2.0 # 标准差乘数
# 执行统计滤波，返回滤波后的点云sor_pcd和对应的索引ind
sor_pcd, ind = pcd.remove_statistical_outlier(num_neighbors, std_ratio)
sor_pcd.paint_uniform_color([0, 0, 1])
print("统计滤波后的点云：", sor_pcd)
# 提取噪声点云
sor_noise_pcd = pcd.select_by_index(ind,invert = True) #除了索引ind以外的点云
print("噪声点云：", sor_noise_pcd)
sor_noise_pcd.paint_uniform_color([1, 0, 0])
# ===========================================================

# 可视化统计滤波后的点云和噪声点云
o3d.visualization.draw_geometries([sor_pcd, sor_noise_pcd])


In [ ]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在估计法线并可视化...")
radius = 0.01   # 搜索半径
max_nn = 30     # 邻域内用于估算法线的最大点数
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius, max_nn))     # 执行法线估计
o3d.visualization.draw_geometries([pcd], point_show_normal=True)#point_show_normal=True显示法线

print("->正在打印前10个点的法向量...")
print(np.asarray(pcd.normals)[:10, :])


In [ ]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在DBSCAN聚类...")
eps = 0.5        # 同一聚类中最大点间距
min_points = 50     # 有效聚类的最小点数
with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(pcd.cluster_dbscan(eps, min_points, print_progress=True))
max_label = labels.max()    # 获取聚类标签的最大值 [-1,0,1,2,...,max_label]，label = -1 为噪声，因此总聚类个数为 max_label + 1
print(f"point cloud has {max_label + 1} clusters")
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0  # labels = -1 的簇为噪声，以黑色显示
pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])
o3d.visualization.draw_geometries([pcd])


In [ ]:
# 布尔索引
import numpy as np

# 创建一个NumPy数组
arr = np.array([1, 2, 3, 4, 5])

# 创建一个布尔数组
mask = arr > 3  # array([False, False, False, True, True])

# 使用布尔索引选择出arr中大于3的元素
selected = arr[mask]  # array([4, 5])

# 使用布尔索引将arr中大于3的元素设置为0
arr[mask] = 0  # array([1, 2, 3, 0, 0])

In [7]:
import numpy as np

colors = [[0.1, 0.2, 0.3, 0.4],
 [0.5, 0.6, 0.7, 0.8],
 [0.9, 1.0, 1.1, 1.2]]

colors = np.array(colors)  # 将列表转换为NumPy数组 #列表不支持切片操作
print(colors[:,:3]) #第一个：表示所有行，第二个：表示列，:3表示前三列

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [ ]:
import open3d as o3d

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("road.pcd")
print(pcd)

print("->正在RANSAC平面分割...")
distance_threshold = 0.2    # 内点到平面模型的最大距离
ransac_n = 3                # 用于拟合平面的采样点数  #三点确定一面 #随机采样三个点
num_iterations = 1000       # 最大迭代次数 #越大越好

# 返回模型系数plane_model和内点索引inliers，并赋值
plane_model, inliers = pcd.segment_plane(distance_threshold, ransac_n, num_iterations)

# 输出平面方程
[a, b, c, d] = plane_model
print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")
#平面方程解释
#ax+by+cz+d=0 其中a,b,c为法向量，d为平面到原点的距离


# 平面内点点云
inlier_cloud = pcd.select_by_index(inliers)
inlier_cloud.paint_uniform_color([0, 0, 1.0])
print(inlier_cloud)

# 平面外点点云
outlier_cloud = pcd.select_by_index(inliers, invert=True)# invert=True表示取反
outlier_cloud.paint_uniform_color([1.0, 0, 0])
print(outlier_cloud)

# 可视化平面分割结果
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])


In [4]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在剔除隐藏点...")
diameter = np.linalg.norm(np.asarray(pcd.get_max_bound()) - np.asarray(pcd.get_min_bound())) #点云的直径
print("定义隐藏点去除的参数")
camera = [0, 0, diameter]       # 视点位置 #[0, diameter, 0]表示视点在点云的上方,距离点云中心diameter的距离 [0, -diameter, 0]表示视点在点云的下方 
#[diameter, 0, 0]表示视点在点云的右方,[0, 0, diameter]表示视点在点云的前方
radius = diameter * 100       # The radius of the sperical projection  球面投影的半径
_, pt_map = pcd.hidden_point_removal(camera, radius)    # 获取视点位置能看到的所有点的索引 pt_map

# 可视点点云
pcd_visible = pcd.select_by_index(pt_map)
pcd_visible.paint_uniform_color([0, 0, 1])	# 可视点为蓝色
print("->可视点个数为：", pcd_visible)
# 隐藏点点云
pcd_hidden = pcd.select_by_index(pt_map, invert = True)
pcd_hidden.paint_uniform_color([1, 0, 0])	# 隐藏点为红色
print("->隐藏点个数为：", pcd_hidden)
print("->正在可视化可视点和隐藏点点云...")
o3d.visualization.draw_geometries([pcd_visible, pcd_hidden])


->正在加载点云... 
PointCloud with 35947 points.
->正在剔除隐藏点...
定义隐藏点去除的参数
->可视点个数为： PointCloud with 11490 points.
->隐藏点个数为： PointCloud with 24457 points.
->正在可视化可视点和隐藏点点云...
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [12]:
import numpy as np

# 计算向量的范数  #欧几里得范数
v = np.array([1, 2, 3])
norm_v = np.linalg.norm(v)
print(norm_v)  # 输出：3.7416573867739413

# 计算矩阵的Frobenius范数（即，矩阵所有元素的平方和的平方根）
m = np.array([[1, 2], [3, 4]])
norm_m = np.linalg.norm(m)
print(norm_m)  # 输出：5.477225575051661

# 计算矩阵的无穷范数（即，矩阵每行元素的绝对值之和的最大值） 1+2=3 3+4=7
norm_m_inf = np.linalg.norm(m, np.inf)
print(norm_m_inf)  # 输出：7.0

print(np.inf)

3.7416573867739413
5.477225575051661
7.0
inf


In [3]:
import open3d as o3d
import numpy as np

# --------------------------- 加载点云 ---------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)
# ==============================================================

# ------------------------- Alpha shapes -----------------------
alpha = 0.01 #值越小三角形网格越细致
print(f"alpha={alpha:.3f}")
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha) #创建三角形网格
mesh.compute_vertex_normals() #这个方法没有参数，返回的是一个更新后的三角形网格对象，其顶点法线已经被计算并存储在`mesh.vertex_normals`属性中。
#[[0.0, 0.0, 1.0],  # 第一个顶点的法线向量 指向z轴正方向

# 创建坐标轴
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.005, origin=[0, 0, 0]) #x红 y绿 z蓝
o3d.visualization.draw_geometries([mesh,coordinate_frame],mesh_show_back_face=True)#mesh_show_back_face=True显示背面
# ==============================================================



->正在加载点云... 
原始点云： PointCloud with 35947 points.
alpha=0.010


In [3]:
import open3d as o3d
import numpy as np

# --------------------------- 加载点云 ---------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)
# ==============================================================

# ------------------------- Alpha shapes -----------------------
alpha = 0.01 #值越小三角形网格越细致
print(f"alpha={alpha:.3f}")
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd, alpha) #创建三角形网格
mesh.compute_vertex_normals() #这个方法没有参数，返回的是一个更新后的三角形网格对象，其顶点法线已经被计算并存储在`mesh.vertex_normals`属性中。
#[[0.0, 0.0, 1.0],  # 第一个顶点的法线向量 指向z轴正方向

# 创建一个可视化窗口
vis = o3d.visualization.Visualizer()
vis.create_window()
# 设置显示背面
vis.get_render_option().mesh_show_back_face = True

# 添加网格和坐标轴
vis.add_geometry(mesh)
vis.add_geometry(o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.005, origin=[0, 0, 0])) #添加坐标轴 x红 y绿 z蓝

# 开始渲染
vis.run()

# 关闭窗口
vis.destroy_window()

->正在加载点云... 
原始点云： PointCloud with 35947 points.
alpha=0.010
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [2]:

import open3d as o3d

# 从PCD文件中读取点云
pcd = o3d.io.read_point_cloud("bunny.pcd")

# 估计点云的法线
pcd.estimate_normals()
# 使用Ball Pivoting算法从点云创建一个网格
radii = [0.005, 0.01, 0.02, 0.04] # 球半径列表
mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
    pcd, o3d.utility.DoubleVector(radii)) #o3d.utility.DoubleVector(radii)将列表转换为DoubleVector类型

# 计算网格的顶点法线
mesh.compute_vertex_normals()

# 从网格中采样点
sampled_pcd = mesh.sample_points_poisson_disk(3000)

# 显示采样后的点云
print("Displaying sampled pointcloud ...")
o3d.visualization.draw_geometries([sampled_pcd])

# 显示重建的网格
print("Displaying reconstructed mesh ...")
o3d.visualization.draw_geometries([mesh])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
->Ball pivoting...
[Open3D WARNING] Read geometry::TriangleMesh failed: unknown file extension.


RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::PointCloud> __cdecl open3d::geometry::TriangleMesh::SamplePointsPoissonDisk(unsigned __int64,double,const class std::shared_ptr<class open3d::geometry::PointCloud>,bool)) D:\a\Open3D\Open3D\cpp\open3d\geometry\TriangleMesh.cpp:527: Input mesh has no triangles.


In [1]:
import open3d as o3d
import numpy as np

# --------------------------- 加载点云 ---------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print("原始点云：", pcd)
# ==============================================================

# ------------------------- Ball pivoting --------------------------
print('run Poisson surface reconstruction')
radius = 0.001   # 搜索半径
max_nn = 30         # 邻域内用于估算法线的最大点数
pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius, max_nn))     # 执行法线估计

with o3d.utility.VerbosityContextManager(o3d.utility.VerbosityLevel.Debug) as cm:
    mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth=12)
print(mesh)
o3d.visualization.draw_geometries([mesh])
# ==============================================================


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
->正在加载点云... 
原始点云： PointCloud with 35947 points.
run Poisson surface reconstruction
[Open3D DEBUG] Input Points / Samples: 35947 / 35946
[Open3D DEBUG] #   Got kernel density: 0.488 (s), 433.141 (MB) / 433.141 (MB) / 433 (MB)
[Open3D DEBUG] #     Got normal field: 0.139 (s), 560.512 (MB) / 560.512 (MB) / 560 (MB)
[Open3D DEBUG] Point weight / Estimated Area: 8.608727e-05 / 3.094579e+00
[Open3D DEBUG] #       Finalized tree: 0.588 (s), 568.438 (MB) / 568.438 (MB) / 699 (MB)
[Open3D DEBUG] #  Set FEM constraints: 0.158 (s), 440.742 (MB) / 568.438 (MB) / 699 (MB)
[Open3D DEBUG] #Set point constraints: 0.107000 (s), 435.086 (MB) / 568.438 (MB) / 699 (MB)
[Open3D DEBUG] Leaf Nodes / Active Nodes / Ghost Nodes: 4910277 / 356368 / 5255377
[Open3D DEBUG] Memory Usage: 435.090 MB
[Open3D DEBUG] # Linear system solved: 0.849 (s),

In [1]:
import open3d as o3d
import numpy as np

# ---------------------- 定义点云体素化函数 ----------------------
def get_point_cloud(_relative_path):
    pcd = o3d.io.read_point_cloud(_relative_path)
    return pcd
# =============================================================

# ------------------------- Ball pivoting --------------------------
print("->Ball pivoting...")
_relative_path = "bunny.pcd"    # 设置相对路径
N = 2000                       # 将点划分为N个体素
pcd = get_point_cloud(_relative_path).voxel_down_sample(voxel_size=0.02)
o3d.visualization.draw_geometries([pcd])

radii = [0.005, 0.01, 0.02, 0.04]
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, o3d.utility.DoubleVector(radii))
o3d.visualization.draw_geometries([pcd, rec_mesh])
# ==============================================================

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
->Ball pivoting...


RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::TriangleMesh> __cdecl open3d::geometry::BallPivoting::Run(const class std::vector<double,class std::allocator<double> > &)) D:\a\Open3D\Open3D\cpp\open3d\geometry\SurfaceReconstructionBallPivoting.cpp:658: ReconstructBallPivoting requires normals


In [1]:
import open3d as o3d

bunny = o3d.data.BunnyMesh()
gt_mesh = o3d.io.read_triangle_mesh(bunny.path)
gt_mesh.compute_vertex_normals()

pcd = gt_mesh.sample_points_poisson_disk(3000)
print("Displaying input pointcloud ...")
o3d.visualization.draw([pcd], point_size=5)

radii = [0.005, 0.01, 0.02, 0.04]
print('Running ball pivoting surface reconstruction ...')
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(
pcd, o3d.utility.DoubleVector(radii))
print("Displaying reconstructed mesh ...")
o3d.visualization.draw([rec_mesh])

In [1]:
import numpy as np

# 生成一个随机数
random_number = np.random.rand()
print(random_number)

# 生成一个包含5个随机数的一维数组
random_array = np.random.rand(5)
print(random_array)

# 生成一个2x3的二维数组，每个元素都是随机数
random_matrix = np.random.rand(2, 3)
print(random_matrix)

0.4232824511759452
[0.96357535 0.45140121 0.07613802 0.92491049 0.82840686]
[[0.57502073 0.8275811  0.54342632]
 [0.00780819 0.89651698 0.81284938]]


In [1]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在计算点云凸包...")
hull, _ = pcd.compute_convex_hull()
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
hull_ls.paint_uniform_color((1, 0, 0))
o3d.visualization.draw_geometries([pcd, hull_ls])


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
->正在加载点云... 
PointCloud with 35947 points.
->正在计算点云凸包...


In [2]:
import open3d as o3d
import numpy as np

print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)

print("->正在计算点云轴向最小包围盒...")
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
print("->正在计算点云最小包围盒...")
obb = pcd.get_oriented_bounding_box()
obb.color = (0, 1, 0)
o3d.visualization.draw_geometries([pcd, aabb, obb])


->正在加载点云... 
PointCloud with 35947 points.
->正在计算点云轴向最小包围盒...
->正在计算点云最小包围盒...


In [5]:
import open3d as o3d
import numpy as np

print("->正在加载点云1... ")
pcd1 = o3d.io.read_point_cloud("bunny.pcd")
print(pcd1)
print("->正在加载点云2...")
pcd2 = o3d.io.read_point_cloud("road.pcd")
print(pcd2)

print("->正在点云1每一点到点云2的最近距离...")
dists = pcd1.compute_point_cloud_distance(pcd2)
dists = np.asarray(dists)
print("->正在打印前10个点...")
print(dists[:10])

print("->正在提取距离大于3.56的点")
ind = np.where(dists > 3.2)[0]
pcd3 = pcd1.select_by_index(ind)
print(pcd3)
o3d.visualization.draw_geometries([pcd3])


->正在加载点云1... 
PointCloud with 35947 points.
->正在加载点云2...
PointCloud with 1144162 points.
->正在点云1每一点到点云2的最近距离...
->正在打印前10个点...
[3.23839644 3.2454794  3.25572124 3.19962587 3.22344055 3.2261811
 3.23844152 3.16783435 3.1664986  3.22188013]
->正在提取距离大于3.56的点
PointCloud with 27496 points.


`pcd.get_axis_aligned_bounding_box()` 和 `pcd.get_oriented_bounding_box()` 都是用于获取点云数据的边界框的方法，但它们的边界框的方向不同。

1. `pcd.get_axis_aligned_bounding_box()`：这个方法返回一个与坐标轴对齐的边界框。也就是说，这个边界框的每个边都平行于坐标轴。这种类型的边界框计算起来比较简单，但可能不会紧密地包围点云。

2. `pcd.get_oriented_bounding_box()`：这个方法返回一个方向边界框，也就是说，这个边界框的方向是根据点云的形状来确定的，而不是简单地与坐标轴对齐。这种类型的边界框可能会更紧密地包围点云，但计算起来比较复杂。



In [1]:
import copy  # 点云深拷贝
import open3d as o3d
import numpy as np

# -------------------------- 加载点云 ------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)
pcd.paint_uniform_color([1,0,0])
print("->pcd质心：",pcd.get_center())
# ===========================================================

# -------------------------- transform ------------------------
print("\n->点云的一般变换")
pcd_T = copy.deepcopy(pcd)
T = np.eye(4 )#单位矩阵
T[ :3, :3] = pcd.get_rotation_matrix_from_xyz((np.pi/6,np.pi/4,0))	# 旋转矩阵 #绕x轴旋转30°，绕y轴旋转45°
T[0,3] = 5.0	# 平移向量的dx
T[1,3] = 3.0	# 平移向量的dy
print("\n->变换矩阵：\n",T)
pcd_T.transform(T)  #输入为4x4的变换矩阵，前3x3为旋转矩阵，后3x1为平移向量
pcd_T.paint_uniform_color([0,0,1])
print("\n->pcd_scale1质心：",pcd_T.get_center())
# ===========================================================

# -------------------------- 可视化 --------------------------
#坐标
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0, 0, 0]) #x红 y绿 z蓝
coordinate_frame_T = copy.deepcopy(coordinate_frame)
coordinate_frame_T.transform(T,)
o3d.visualization.draw_geometries([pcd, pcd_T, coordinate_frame, coordinate_frame_T])
# ===========================================================


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
->正在加载点云... 
PointCloud with 35947 points.
->pcd质心： [-0.02675991  0.09521606  0.00894711]

->点云的一般变换

->变换矩阵：
 [[ 0.70710678  0.          0.70710678  5.        ]
 [ 0.35355339  0.8660254  -0.35355339  3.        ]
 [-0.61237244  0.5         0.61237244  0.        ]
 [ 0.          0.          0.          1.        ]]

->pcd_scale1质心： [4.98740445 3.06983519 0.06947403]
[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [5]:
import copy  # 点云深拷贝
import open3d as o3d

# -------------------------- 加载点云 ------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
pcd.paint_uniform_color([0, 0, 0])
print(pcd)
print(f'pcd质心：{pcd.get_center()}')
# ===========================================================

# -------------------------- 点云平移 ------------------------
print("\n->沿X轴平移0.2m")
pcd_tx = copy.deepcopy(pcd).translate((0.2, 0.2, 0.2)) #沿x轴平移0.2m y轴平移0.2m z轴平移0.2m ,relative=True表示相对于原点平移
pcd_tx.paint_uniform_color([1, 0, 0])
print(pcd_tx)
print(f'pcd_tx质心：{pcd_tx.get_center()}')

print("\n->将点云质心平移到指定位置")
pcd_new = copy.deepcopy(pcd_tx).translate((0.2, 0.2, 0.2),relative=False) # relative=False表示质心移动到指定位置，不是平移的距离
#pcd_new = copy.deepcopy(pcd_tx).translate((0.2, 0.2, 0.2),False)  # relative 可以省略
pcd_new.paint_uniform_color([0, 1, 0])
print(pcd_new)
print(f'pcd_new：{pcd_new.get_center()}')
# ===========================================================

# -------------------------- 可视化 --------------------------
o3d.visualization.draw_geometries([pcd, pcd_tx, pcd_new])
# ===========================================================


->正在加载点云... 
PointCloud with 35947 points.
pcd质心：[-0.02675991  0.09521606  0.00894711]

->沿X轴平移0.2m
PointCloud with 35947 points.
pcd_tx质心：[0.17324009 0.29521606 0.20894711]

->将点云质心平移到指定位置
PointCloud with 35947 points.
pcd_new：[0.2 0.2 0.2]


In [8]:
import copy  # 点云深拷贝
import open3d as o3d
import numpy as np

# -------------------------- 加载点云 ------------------------
print("->正在加载点云... ")
pcd = o3d.io.read_point_cloud("bunny.pcd")
print(pcd)
pcd.paint_uniform_color([1,0,0])
print("->pcd质心：",pcd.get_center())
# ===========================================================

# -------------------------- 点云旋转 ------------------------
print("\n->采用欧拉角进行点云旋转")
pcd_EulerAngle = copy.deepcopy(pcd)
R1 = pcd.get_rotation_matrix_from_xyz((0,np.pi/2,0))
print("旋转矩阵：\n",R1)
pcd_EulerAngle.rotate(R1,center = (0.1,0.1,0.1))    # 指定旋转中心 #会改变点云的质心 若不指定旋转中心，则不会改变点云的质心
pcd_EulerAngle.paint_uniform_color([0,0,1])
print("\n->pcd_EulerAngle质心：",pcd_EulerAngle.get_center())
# ===========================================================

# -------------------------- 可视化 --------------------------
#坐标
coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1, origin=[0, 0, 0]) #x红 y绿 z蓝
coordinate_frame_EulerAngle = copy.deepcopy(coordinate_frame)
coordinate_frame_EulerAngle.rotate(R1,center = (0.1,0.1,0.1))
o3d.visualization.draw_geometries([pcd, pcd_EulerAngle, coordinate_frame, coordinate_frame_EulerAngle])
# ===========================================================


->正在加载点云... 
PointCloud with 35947 points.
->pcd质心： [-0.02675991  0.09521606  0.00894711]

->采用欧拉角进行点云旋转
旋转矩阵：
 [[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]

->pcd_EulerAngle质心： [0.00894711 0.09521606 0.22675991]
